/**
 * dsh-plugin-otools-dbm client bundle - GENERATED by scripts/wrap-client.mjs.
 * Do not edit; the source of truth is src/client/index.js (npm run build).
 */
window.__ModuleLoader__.load({
  id: 'dsh-plugin-otools-dbm',
  factory: (require) => {
    var module = { exports: {} };
    var exports = module.exports;
/**
 * The browser half: a sidebar entry, and a full-page panel that hosts the app.
 *
 * Unlike this repo's other panel plugins, the UI here is NOT drawn by this bundle.
 * The reference plugin's interface is 22k lines of Vue 3 + Element Plus, and the
 * brief was to reproduce it exactly — so the Vue app is copied verbatim, built by
 * Vite into `lib/webview/`, served by the host half at
 * `/dsh-plugin-otools-dbm/app/`, and shown in a same-origin iframe. This file is
 * the 300 lines that get it onto the screen and keep it in step with the shell:
 * language, light/dark, and "another panel just opened, stand down".
 *
 * The iframe is created on FIRST OPEN, never at boot. The app is a few megabytes of
 * JS; a user who never clicks the database icon should not pay for it.
 *
 * Failure policy mirrors the sibling plugins: DOM problems are logged, never
 * thrown — the web shell must not fail its boot because a panel seat is missing on
 * some DSH layout.
 */
(function () {
  'use strict'

  const PLUGIN_ID = 'dsh-plugin-otools-dbm'
  const ROUTE_PREFIX = '/' + PLUGIN_ID
  const APP_PATH = ROUTE_PREFIX + '/app/'
  const STYLE_ID = PLUGIN_ID + '-style'
  const PANEL_NAME = PLUGIN_ID
  const ACTIVATE_EVENT = 'dsh-panel-activate'
  const OPEN_ATTR = 'data-dsh-dbm-open'
  const ENTRY_SELECTOR = '[data-dsh-otools-dbm-entry]'
  const VIEW_SELECTOR = '[data-dsh-dbm-view]'
  const LOG = '[' + PLUGIN_ID + ']'

  /** Seats in the DSH shell, across the layout generations it has shipped. */
  const CONVERSATION_SELECTOR =
    '[data-pane="conversation"], [class*="centerCol"], .dshDesktopConversationSurface'
  const SIDEBAR_SELECTOR =
    '[data-pane="sidebar"], [class*="sidebarCol"], .dshDesktopUpstreamSidebar, .dshDesktopSidebarSurface'
  /** Sibling panel plugins: entries stay grouped and only one panel is open. */
  const SIBLING_ENTRIES =
    '[data-dsh-cgtb-entry], [data-dsh-taskboard-entry], [data-dsh-repopanel-entry],'
    + ' [data-dsh-ssh-entry], [data-dsh-otools-git-entry], [data-dsh-automation-entry]'

  const STYLES = `
.dsh-dbm-entry {
  display: flex; align-items: center; gap: 8px; position: relative;
  width: calc(100% - 8px); margin: 2px 4px; padding: 6px 10px;
  border: none; border-radius: 8px; background: transparent;
  color: var(--dsw-alias-label-secondary, var(--dsw-text-secondary, #7f8fa4));
  font: inherit; font-size: 13px; cursor: pointer; text-align: left; box-sizing: border-box;
}
.dsh-dbm-entry:hover {
  background: var(--dsw-alias-interactive-bg-hover, var(--dsw-hover, rgba(128, 128, 128, .12)));
  color: var(--dsw-alias-label-primary, var(--dsw-text-primary, inherit));
}
.dsh-dbm-entry[data-active="true"] {
  background: var(--dsw-alias-bg-layer-2, var(--dsw-active, rgba(128, 128, 128, .18)));
  color: var(--dsw-alias-label-primary, var(--dsw-text-primary, inherit)); font-weight: 500;
}
.dsh-dbm-entry-icon { display: inline-flex; flex: none; color: #2370c6; }
.dsh-dbm-entry-label { flex: none; }
[data-sidebar-collapsed] [data-dsh-otools-dbm-entry],
[class*="_collapsed"] [data-dsh-otools-dbm-entry] {
  width: 36px; height: 36px; min-width: 36px; margin: 0 0 12px; padding: 0;
  justify-content: center; gap: 0; text-align: center;
}
[data-sidebar-collapsed] [data-dsh-otools-dbm-entry] .dsh-dbm-entry-label,
[class*="_collapsed"] [data-dsh-otools-dbm-entry] .dsh-dbm-entry-label { display: none; }

html[${OPEN_ATTR}] [data-pane="conversation"] > *:not(${VIEW_SELECTOR}),
html[${OPEN_ATTR}] [class*="centerCol"] > *:not(${VIEW_SELECTOR}),
html[${OPEN_ATTR}] .dshDesktopConversationSurface > *:not(${VIEW_SELECTOR}) { display: none !important; }
.dsh-dbm-view { display: none; }
html[${OPEN_ATTR}] .dsh-dbm-view {
  display: flex; flex-direction: column; height: 100%; min-height: 0; overflow: hidden;
}
.dsh-dbm-frame { flex: 1; width: 100%; min-height: 0; border: 0; display: block; background: transparent; }
.dsh-dbm-fallback {
  display: flex; flex-direction: column; align-items: center; justify-content: center;
  gap: 8px; height: 100%; padding: 24px; text-align: center; font-size: 13px;
  color: var(--dsw-alias-label-secondary, #7f8fa4);
}
`

  /** 20x20 database icon, drawn rather than imported so the bundle stays one file. */
  const ICON = '<svg viewBox="0 0 24 24" width="15" height="15" fill="none" stroke="currentColor"'
    + ' stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">'
    + '<ellipse cx="12" cy="5.5" rx="7.5" ry="3"/>'
    + '<path d="M4.5 5.5v6c0 1.66 3.36 3 7.5 3s7.5-1.34 7.5-3v-6"/>'
    + '<path d="M4.5 11.5v6c0 1.66 3.36 3 7.5 3s7.5-1.34 7.5-3v-6"/></svg>'

  const state = {
    open: false,
    disposed: false,
    entry: null,
    view: null,
    frame: null,
    locale: '',
    theme: '',
  }

  function log(message, error) {
    if (error === undefined) {
      console.warn(LOG + ' ' + message)
      return
    }
    console.warn(LOG + ' ' + message, error && error.message ? error.message : error)
  }

  function injectStyles() {
    if (document.getElementById(STYLE_ID) !== null) {
      return
    }
    const style = document.createElement('style')
    style.id = STYLE_ID
    style.textContent = STYLES
    document.head.appendChild(style)
  }

  // ------------------------------------------------------------------- theme
  /**
   * Which theme the shell is in.
   *
   * DSH does not expose that as a variable this bundle can read directly, so this
   * walks the three places it can show up, in order of reliability, and falls back
   * to the luminance of the shell's own background token — which is correct by
   * construction whatever the shell calls its themes.
   */
  function detectTheme() {
    const root = document.documentElement
    const explicit = String(root.dataset.theme || root.getAttribute('data-dsw-theme') || '')
    if (explicit.indexOf('dark') !== -1) {
      return 'dark'
    }
    if (explicit.indexOf('light') !== -1) {
      return 'light'
    }
    if (root.classList.contains('dark')) {
      return 'dark'
    }
    if (root.classList.contains('light')) {
      return 'light'
    }
    const token = readColorToken('--dsw-alias-bg-base') || readColorToken('--dsw-bg')
    if (token !== null) {
      return token < 0.5 ? 'dark' : 'light'
    }
    if (typeof window.matchMedia === 'function') {
      return window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light'
    }
    return 'light'
  }

  /** Relative luminance of a CSS custom property, or null when unreadable. */
  function readColorToken(name) {
    let raw = ''
    try {
      raw = getComputedStyle(document.documentElement).getPropertyValue(name).trim()
    } catch (error) {
      return null
    }
    if (raw.length === 0) {
      return null
    }
    let parts = null
    const hex = /^#([0-9a-f]{3}|[0-9a-f]{6})$/i.exec(raw)
    if (hex !== null) {
      const value = hex[1].length === 3
        ? hex[1].split('').map(function (char) { return parseInt(char + char, 16) })
        : [raw.slice(1, 3), raw.slice(3, 5), raw.slice(5, 7)].map(function (pair) { return parseInt(pair, 16) })
      parts = value
    } else {
      const rgb = /rgba?\(\s*([\d.]+)[\s,]+([\d.]+)[\s,]+([\d.]+)/i.exec(raw)
      if (rgb !== null) {
        parts = [Number(rgb[1]), Number(rgb[2]), Number(rgb[3])]
      }
    }
    if (parts === null || parts.some(function (value) { return !isFinite(value) })) {
      return null
    }
    return (0.2126 * parts[0] + 0.7152 * parts[1] + 0.0722 * parts[2]) / 255
  }

  /** Tell the panel about a theme change without reloading it. */
  function pushTheme() {
    const theme = detectTheme()
    if (theme === state.theme) {
      return
    }
    state.theme = theme
    postToFrame({ type: 'dbm:theme', value: theme })
  }

  function postToFrame(message) {
    if (state.frame === null || state.frame.contentWindow === null) {
      return
    }
    try {
      // Same-origin by construction (the host serves both), so '*' costs nothing
      // and survives the shell being reached through a proxy with a rewritten host.
      state.frame.contentWindow.postMessage(message, '*')
    } catch (error) {
      log('postMessage failed', error)
    }
  }

  // -------------------------------------------------------------------- seats
  function sidebarRoot() {
    const column = document.querySelector(SIDEBAR_SELECTOR)
    if (column === null) {
      return null
    }
    const logoRow = column.querySelector('[class*="logoRow"]')
    return (logoRow !== null ? logoRow.parentElement : column.firstElementChild) || null
  }

  function conversationColumn() {
    return document.querySelector(CONVERSATION_SELECTOR)
  }

  function createEntry() {
    const button = document.createElement('button')
    button.type = 'button'
    button.className = 'dsh-dbm-entry'
    button.setAttribute('data-dsh-otools-dbm-entry', '')
    button.setAttribute('aria-label', '数据库')
    button.title = '鲨鱼数据库'

    const icon = document.createElement('span')
    icon.className = 'dsh-dbm-entry-icon'
    icon.setAttribute('aria-hidden', 'true')
    icon.innerHTML = ICON

    const label = document.createElement('span')
    label.className = 'dsh-dbm-entry-label'
    label.textContent = '数据库'

    button.appendChild(icon)
    button.appendChild(label)
    button.addEventListener('click', function () {
      setOpen(!state.open)
    })
    return button
  }

  /** Keep the entry with the other panel plugins' entries. */
  function placeEntry() {
    if (state.entry === null) {
      return
    }
    const root = sidebarRoot()
    if (root === null || !root.isConnected) {
      return
    }
    if (state.entry.parentElement === root) {
      return
    }
    const family = Array.prototype.filter.call(root.children, function (child) {
      return child.matches !== undefined && child.matches(ENTRY_SELECTOR + ', ' + SIBLING_ENTRIES)
    })
    if (family.length > 0) {
      root.insertBefore(state.entry, family[family.length - 1].nextElementSibling)
      return
    }
    const nested = root.querySelector('button[class*="newSession"]')
    if (nested !== null && nested.parentElement !== null) {
      const row = nested.parentElement === root ? nested : nested.closest('[class*="logoRow"]')
      if (row !== null) {
        root.insertBefore(state.entry, row.nextElementSibling)
        return
      }
    }
    root.appendChild(state.entry)
  }

  /** Attach (or re-attach) the view as a trailing child of the centre column. */
  function ensureView() {
    const column = conversationColumn()
    if (column === null) {
      return
    }
    if (state.view === null || !state.view.isConnected) {
      if (state.view !== null && state.view.parentElement !== null) {
        state.view.remove()
      }
      state.view = document.createElement('div')
      state.view.className = 'dsh-dbm-view'
      state.view.setAttribute('data-dsh-dbm-view', '')
      state.frame = null
    }
    if (state.view.parentElement !== column) {
      column.appendChild(state.view)
    }
  }

  /**
   * Build the iframe.
   *
   * The language comes from the host (`/health` → the locale DSH resolved from
   * DSH_DESKTOP_LANG / LC_ALL / LANG), so the panel matches the shell around it
   * rather than guessing from the browser. A failed probe is not fatal: the panel
   * then falls back to `navigator.language` on its own.
   */
  async function ensureFrame() {
    ensureView()
    if (state.view === null || state.frame !== null) {
      return
    }

    if (state.locale.length === 0) {
      try {
        const response = await fetch(ROUTE_PREFIX + '/health', { headers: { accept: 'application/json' } })
        const payload = await response.json()
        const locale = payload && payload.value ? payload.value.locale : ''
        state.locale = typeof locale === 'string' ? locale : ''
      } catch (error) {
        log('locale probe failed, falling back to the browser language', error)
        state.locale = ''
      }
    }

    state.theme = detectTheme()
    const query = new URLSearchParams()
    if (state.locale.length > 0) {
      query.set('lang', state.locale)
    }
    query.set('theme', state.theme)

    const frame = document.createElement('iframe')
    frame.className = 'dsh-dbm-frame'
    frame.setAttribute('title', '鲨鱼数据库')
    frame.setAttribute('allow', 'clipboard-read; clipboard-write')
    frame.src = APP_PATH + '?' + query.toString()
    frame.addEventListener('error', function () {
      showFallback('面板加载失败，请刷新页面重试。')
    })

    state.view.replaceChildren(frame)
    state.frame = frame
  }

  function showFallback(message) {
    if (state.view === null) {
      return
    }
    const box = document.createElement('div')
    box.className = 'dsh-dbm-fallback'
    const title = document.createElement('div')
    title.textContent = message
    box.appendChild(title)
    state.view.replaceChildren(box)
    state.frame = null
  }

  function renderEntry() {
    if (state.entry === null) {
      return
    }
    state.entry.setAttribute('data-active', state.open ? 'true' : 'false')
  }

  function ensureMounted() {
    if (state.disposed) {
      return
    }
    try {
      if (state.entry === null || !state.entry.isConnected) {
        state.entry = createEntry()
      }
      placeEntry()
      if (conversationColumn() !== null) {
        ensureView()
        // Re-parenting an iframe reloads it, so the frame is only rebuilt when the
        // view itself was replaced by a shell repaint.
        if (state.open && state.frame === null) {
          void ensureFrame()
        }
      }
      renderEntry()
    } catch (error) {
      log('seat mount failed', error)
    }
  }

  function setOpen(open) {
    state.open = open
    if (open) {
      document.documentElement.setAttribute(OPEN_ATTR, '')
      document.dispatchEvent(new CustomEvent(ACTIVATE_EVENT, { detail: PANEL_NAME }))
      void ensureFrame()
    } else {
      document.documentElement.removeAttribute(OPEN_ATTR)
    }
    renderEntry()
  }

  // --------------------------------------------------------------------- boot
  const booted = { running: false }

  function apply(ctx) {
    if (typeof window === 'undefined' || typeof document === 'undefined') {
      return
    }
    if (booted.running) {
      return
    }
    booted.running = true

    let observer = null
    let timer = null
    let onActivate = null
    let onKeyDown = null
    let media = null
    let onMedia = null

    function dispose() {
      if (state.disposed) {
        return
      }
      state.disposed = true
      if (timer !== null) {
        clearInterval(timer)
      }
      if (observer !== null) {
        try {
          observer.disconnect()
        } catch (error) {
          /* already gone */
        }
      }
      if (onActivate !== null) {
        document.removeEventListener(ACTIVATE_EVENT, onActivate)
      }
      if (onKeyDown !== null) {
        document.removeEventListener('keydown', onKeyDown)
      }
      if (media !== null && onMedia !== null && typeof media.removeEventListener === 'function') {
        media.removeEventListener('change', onMedia)
      }
      document.documentElement.removeAttribute(OPEN_ATTR)
      if (state.entry !== null) {
        try {
          state.entry.remove()
        } catch (error) {
          /* already gone */
        }
        state.entry = null
      }
      if (state.view !== null) {
        try {
          state.view.remove()
        } catch (error) {
          /* already gone */
        }
        state.view = null
      }
      state.frame = null
      state.open = false
      const style = document.getElementById(STYLE_ID)
      if (style !== null) {
        style.remove()
      }
      booted.running = false
    }

    try {
      injectStyles()
      ensureMounted()

      // The DSH shell re-renders its own tree; an observer plus a slow interval
      // keep the seats attached across those repaints.
      observer = new MutationObserver(function () {
        ensureMounted()
        pushTheme()
      })
      observer.observe(document.body || document.documentElement, {
        childList: true,
        subtree: true,
        attributes: true,
        attributeFilter: ['class', 'data-theme', 'data-dsw-theme'],
      })
      timer = setInterval(ensureMounted, 3000)

      onActivate = function (event) {
        if (state.disposed) {
          return
        }
        if (event.detail !== undefined && event.detail !== PANEL_NAME && state.open) {
          setOpen(false)
        }
      }
      document.addEventListener(ACTIVATE_EVENT, onActivate)

      onKeyDown = function (event) {
        if (state.disposed || !state.open) {
          return
        }
        // Escape closes the panel only when the app itself did not use it — the
        // panel is full of dialogs that own Escape, so the iframe gets it first
        // and this only sees the key when focus is outside the frame.
        if (event.key === 'Escape' && document.activeElement !== state.frame) {
          setOpen(false)
        }
      }
      document.addEventListener('keydown', onKeyDown)

      if (typeof window.matchMedia === 'function') {
        media = window.matchMedia('(prefers-color-scheme: dark)')
        onMedia = function () {
          pushTheme()
        }
        if (typeof media.addEventListener === 'function') {
          media.addEventListener('change', onMedia)
        }
      }

      if (ctx !== undefined && ctx !== null && typeof ctx.effect === 'function') {
        // cordis: effect(fn) runs fn and keeps its return value as the disposer.
        ctx.effect(function () {
          return dispose
        }, PLUGIN_ID + ': client mount')
      } else {
        window.addEventListener('beforeunload', dispose, { once: true })
      }
    } catch (error) {
      console.error(LOG + ' client boot failed', error)
      dispose()
    }
  }

  // The wrap step evaluates this file inside window.__ModuleLoader__.load with a
  // CommonJS `module` in scope; a plain Node require() gets the same shape.
  if (typeof module !== 'undefined' && module !== null && module.exports !== undefined) {
    module.exports = {
      name: PLUGIN_ID + '/client',
      inject: [],
      apply: apply,
    }
  }
})()
    return module.exports;
  }
});
