/**
 * Wraps the src/client parts into the DSH browser module-loader shape every
 * published client plugin uses (window.__ModuleLoader__.load), producing the
 * single-file lib/client.js that package.json exports as "./client".
 *
 * Unlike the sibling repopanel plugin the browser half is too big for one file,
 * so it is kept as an ORDERED LIST of fragments that are concatenated inside a
 * single IIFE. They therefore share one lexical scope exactly as one big file
 * would: a fragment may use anything an earlier fragment declared, and function
 * declarations hoist across the whole bundle. Every fragment is a plain script
 * body — no IIFE, no import/export — and every top-level name must be unique
 * across the list (`npm run check` catches a collision as a syntax error).
 *
 * The client source is dependency-free vanilla DOM: it never requires anything,
 * so the loader `require` argument is simply unused. The inner IIFE assigns
 * `module.exports` when it sees a CommonJS `module` — exactly what the factory
 * provides — and the factory returns it. Kept ASCII-safe in its own markup: the
 * file is LF-only with a single trailing newline, no BOM.
 *
 * @module dsh-plugin-otools-git/scripts/wrap-client
 */
import { readFile, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = dirname(dirname(fileURLToPath(import.meta.url)))

/** Loader plugin id (matches the package name and the cordis.patch.yml row). */
export const PLUGIN_ID = 'dsh-plugin-otools-git'

/**
 * Concatenation order. Roughly: vocabulary → helpers → styles → model →
 * transport → widgets → views → dialogs → boot. `boot.js` must stay last: it
 * both defines apply() and performs the module.exports assignment.
 */
export const CLIENT_PARTS = [
  'vocab.js',
  'dom.js',
  'styles.js',
  'model.js',
  'api.js',
  'widgets.js',
  'icons.js',
  'repo-tree.js',
  'status-panel.js',
  'commit-box.js',
  'diff-view.js',
  'history.js',
  'graph.js',
  'branches.js',
  'stash.js',
  'remotes.js',
  'submodules.js',
  'worktrees.js',
  'ops.js',
  'settings.js',
  'shell.js',
  'boot.js',
]

/** Generated-file banner (plain ASCII comment). */
export const GENERATED_HEADER = [
  '/**',
  ' * dsh-plugin-otools-git client bundle - GENERATED by scripts/wrap-client.mjs.',
  ' * Do not edit; the source of truth is src/client/*.js (npm run build).',
  ' */',
  '',
].join('\n')

/** Wrap the ordered client fragments for the DSH module loader. */
export function wrapClient(parts) {
  const body = parts
    .map((part) => {
      const source = String(part.source).replace(/\s+$/, '')
      return `// ===== src/client/${part.name} =====\n${source}`
    })
    .join('\n\n')
  return (
    GENERATED_HEADER +
    'window.__ModuleLoader__.load({\n' +
    `  id: '${PLUGIN_ID}',\n` +
    '  factory: (require) => {\n' +
    '    var module = { exports: {} };\n' +
    '    var exports = module.exports;\n' +
    '    (function () {\n' +
    "      'use strict';\n" +
    `${body}\n` +
    '    })();\n' +
    '    return module.exports;\n' +
    '  }\n' +
    '});\n'
  )
}

/** Read every src/client fragment and write the wrapped lib/client.js. */
export async function buildClient() {
  const parts = []
  for (const name of CLIENT_PARTS) {
    parts.push({ name, source: await readFile(join(root, 'src', 'client', name), 'utf8') })
  }
  const out = join(root, 'lib', 'client.js')
  await writeFile(out, wrapClient(parts), 'utf8')
  return out
}
