/**
 * Wraps the browser half into the dsh module-loader shape every published client
 * plugin uses (`window.__ModuleLoader__.load`), producing the single-file
 * lib/client.js that package.json exports as "./client".
 *
 * Unlike its taskboard sibling this step also INLINES `src/shared/*.js` ahead of
 * the client body, in dependency order. The loader wrapper provides a CommonJS
 * `module` and a `require` that resolves only the dsh module graph, so a browser
 * bundle cannot import a sibling file — and the alternative, keeping a second
 * hand-maintained copy of the geometry in the client, is exactly the drift that
 * makes cards overlap their frames at one zoom and not another. One source of
 * truth, inlined at build time.
 *
 * The transform is deliberately dumb (strip relative imports, strip the `export`
 * keyword, concatenate) rather than a real bundler: the shared modules are
 * hand-written to suit it, and `npm run check` syntax-checks the result.
 *
 * @module dsh-plugin-canvas/scripts/wrap-client
 */
import { readFile, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { Script } from 'node:vm'

const root = dirname(dirname(fileURLToPath(import.meta.url)))

/** Loader plugin id (matches the package name and the cordis.patch.yml row). */
export const PLUGIN_ID = 'dsh-plugin-canvas'

/** Shared modules inlined into the bundle, in dependency order. */
export const SHARED_MODULES = ['lang.js', 'units.js', 'layout.js', 'snap.js', 'model.js', 'derive.js']

/** Browser-only modules inlined ahead of the entry, in dependency order. The
 *  entry (`src/client/index.js`) comes last and is what assigns module.exports. */
export const CLIENT_MODULES = [
  'styles.js',
  'state.js',
  'viewport.js',
  'render.js',
  'commands.js',
  'interact.js',
  'dock.js',
]

/** Generated-file banner (plain ASCII comment). */
export const GENERATED_HEADER = [
  '/**',
  ' * dsh-plugin-canvas client bundle - GENERATED by scripts/wrap-client.mjs.',
  ' * Do not edit; the sources of truth are src/client/index.js and src/shared/*.js',
  ' * (npm run build).',
  ' */',
  '',
].join('\n')

/**
 * Strip a shared module down to something that can be concatenated inside one
 * function scope: relative imports removed (the names come from a sibling module
 * in the same scope), `export` keyword removed.
 */
export function inlineModule(source) {
  return String(source)
    .replace(/^import\s*\{[^}]*\}\s*from\s*'\.\/[^']+\.js'\r?\n/gm, '')
    .replace(/^import[\s\S]*?from '\.\/[^']+\.js'\r?\n/gm, '')
    .replace(/^export (?=(async function|const|function|class|let|var) )/gm, '')
    .replace(/\s+$/, '')
}

/** Wrap the inlined modules plus the client entry for the dsh loader. */
export function wrapClient(source, shared = []) {
  const body = String(source).replace(/\s+$/, '')
  const inlined = shared
    .map(({ name, code }) => `    // ---- inlined ${name} ----\n${code}`)
    .join('\n\n')
  return (
    GENERATED_HEADER +
    'window.__ModuleLoader__.load({\n' +
    `  id: '${PLUGIN_ID}',\n` +
    '  factory: (require) => {\n' +
    '    var module = { exports: {} };\n' +
    '    var exports = module.exports;\n' +
    `${inlined}\n\n` +
    `${body}\n` +
    '    return module.exports;\n' +
    '  }\n' +
    '});\n'
  )
}

/**
 * Refuse to write a bundle the browser cannot parse.
 *
 * The browser loads this file as a CLASSIC SCRIPT, where a surviving `import` or
 * `export` statement is a SyntaxError — the file never executes, so
 * `__ModuleLoader__.load` is never reached and the loader reports the bundle as
 * "loaded without registering". `node --check` (what scripts/check.mjs runs)
 * cannot see it: package.json says `type: module`, so it parses lib/client.js as
 * ESM, where both keywords are perfectly legal. `new Script()` parses in script
 * mode, which is the mode that actually matters.
 *
 * This lives in the build rather than in check.mjs on purpose: `npm pack` runs
 * `prepack` → build, and a tarball is how the bundle reaches a user.
 *
 * @param {string} bundle
 */
export function assertLoadableInBrowser(bundle) {
  try {
    new Script(bundle, { filename: 'lib/client.js' })
  } catch (error) {
    throw new Error(
      `wrap-client produced a bundle the browser cannot parse as a script: ${error.message}\n` +
        'A relative import in src/shared or src/client most likely escaped inlineModule().'
    )
  }
  // A belt-and-braces scan for the one transform that has actually regressed:
  // `new Script` above already rejects a top-level import/export, but a leftover
  // one nested where it happens to parse would still be a broken module boundary.
  const leftover = bundle
    .split('\n')
    .map((line, index) => ({ line, number: index + 1 }))
    .filter(({ line }) => /^\s*(import\s*[{('"*]|export\s)/.test(line))
  if (leftover.length > 0) {
    const where = leftover.map(({ number, line }) => `  ${number}: ${line.trim()}`).join('\n')
    throw new Error(`wrap-client left ${leftover.length} module statement(s) in the bundle:\n${where}`)
  }
}

/** Read every inlined module and the client entry, write the wrapped bundle. */
export async function buildClient() {
  const parts = []
  for (const name of SHARED_MODULES) {
    const code = inlineModule(await readFile(join(root, 'src', 'shared', name), 'utf8'))
    parts.push({ name: `src/shared/${name}`, code })
  }
  for (const name of CLIENT_MODULES) {
    const code = inlineModule(await readFile(join(root, 'src', 'client', name), 'utf8'))
    parts.push({ name: `src/client/${name}`, code })
  }
  const source = inlineModule(await readFile(join(root, 'src', 'client', 'index.js'), 'utf8'))
  const bundle = wrapClient(source, parts)
  assertLoadableInBrowser(bundle)
  const out = join(root, 'lib', 'client.js')
  await writeFile(out, bundle, 'utf8')
  return out
}
