/**
 * Wraps src/client/index.js into the DSH browser module-loader shape every
 * published client plugin uses (window.__ModuleLoader__.load), producing the
 * single-file lib/client.js that package.json exports as "./client".
 *
 * The client source is dependency-free vanilla DOM: it never requires anything, so
 * the loader `require` argument is simply unused. The inner IIFE assigns
 * `module.exports` when it sees a CommonJS `module` — exactly what the factory
 * provides — and the factory returns it.
 *
 * @module dsh-plugin-automation/scripts/wrap-client
 */
import { readFile, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = dirname(dirname(fileURLToPath(import.meta.url)))

/** Loader plugin id (matches the package name and the cordis.patch.yml row). */
export const PLUGIN_ID = 'dsh-plugin-automation'

/** Generated-file banner (plain ASCII comment). */
export const GENERATED_HEADER = [
  '/**',
  ' * dsh-plugin-automation client bundle - GENERATED by scripts/wrap-client.mjs.',
  ' * Do not edit; the source of truth is src/client/index.js (npm run build).',
  ' */',
  '',
].join('\n')

/** Wrap one client source file for the DSH module loader. */
export function wrapClient(source) {
  const body = String(source).replace(/\s+$/, '')
  return (
    GENERATED_HEADER +
    'window.__ModuleLoader__.load({\n' +
    `  id: '${PLUGIN_ID}',\n` +
    '  factory: (require) => {\n' +
    '    var module = { exports: {} };\n' +
    '    var exports = module.exports;\n' +
    `${body}\n` +
    '    return module.exports;\n' +
    '  }\n' +
    '});\n'
  )
}

/** Read src/client/index.js and write the wrapped lib/client.js. */
export async function buildClient() {
  const source = await readFile(join(root, 'src', 'client', 'index.js'), 'utf8')
  const out = join(root, 'lib', 'client.js')
  await writeFile(out, wrapClient(source), 'utf8')
  return out
}
