/**
 * dsh-plugin-longread client bundle - GENERATED by scripts/wrap-client.mjs.
 * Do not edit; the source of truth is src/client/index.js (npm run build).
 */
window.__ModuleLoader__.load({
  id: 'dsh-plugin-longread',
  factory: (require) => {
    var module = { exports: {} };
    var exports = module.exports;
/**
 * Browser half of dsh-plugin-longread — the reading surface, dressed as a DSH
 * session. A chapter arrives from the host as a turn plan (fake prompt, fake
 * reasoning, fake tool calls, real prose) and this file plays it back: tool rows
 * flip from running to done, then the prose types itself out.
 *
 * Dependency-free vanilla DOM on purpose, like its sibling plugins: the host
 * serves everything at /dsh-plugin-longread and this bundle only talks to it, so
 * it needs no React runtime and no @deepseek-ai/* package in the browser.
 *
 * Colours come from the shell's own theme tokens (`--dsw-alias-*`) with hard
 * fallbacks, so the panel follows light/dark without asking anyone.
 *
 * Export shape: `name` / `inject` / `apply` (no default export). The build
 * (scripts/wrap-client.mjs) wraps this file in the DSH module loader
 * (`window.__ModuleLoader__.load`), which provides a CommonJS `module`, so this
 * file assigns `module.exports` when present and is otherwise inert.
 *
 * Failure policy mirrors the reference plugins: DOM problems are logged, never
 * thrown — the web shell must not fail boot because a seat is missing on some
 * DSH layout. And nothing here is allowed to reach the agent: this plugin only
 * ever reads its own routes.
 *
 * @module dsh-plugin-longread/client
 */
(function () {
  'use strict'

  const PLUGIN_ID = 'dsh-plugin-longread'
  const ROUTE_PREFIX = '/dsh-plugin-longread'
  const STYLE_ID = 'dsh-plugin-longread-style'
  const PANEL_NAME = 'dsh-plugin-longread'
  const ACTIVATE_EVENT = 'dsh-panel-activate'
  const OPEN_ATTR = 'data-dsh-lr-open'
  const ENTRY_SELECTOR = '[data-dsh-lr-entry]'
  const VIEW_SELECTOR = '[data-dsh-lr-view]'
  const CONVERSATION_SELECTOR = '[data-pane="conversation"], [class*="centerCol"], .dshDesktopConversationSurface'
  const SIDEBAR_SELECTOR = '[data-pane="sidebar"], [class*="sidebarCol"], .dshDesktopUpstreamSidebar, .dshDesktopSidebarSurface'
  const OTHER_OPEN_ATTRS = ['data-dsh-cgtb-open', 'data-dsh-taskboard-active', 'data-dsh-rp-open']
  const LOG = '[' + PLUGIN_ID + ']'

  /** Instant replay is capped: a chapter resumed at turn 90 should not build 90 turns of DOM. */
  const REPLAY_TURNS = 6

  /** How long a fake tool call spends in its running state, at most. */
  const MAX_CALL_MS = 900

  /** Pause between an assistant reply and the next auto-played turn. */
  const AUTO_GAP_MS = 620

  // ---------------------------------------------------------------- helpers
  /**
   * Build an element. Text children are set through textContent (or wrapped in a
   * span when mixed with elements) rather than appended as text nodes, so the
   * same code runs under the test DOM, which has no createTextNode.
   */
  function el(tag, attrs) {
    const node = document.createElement(tag)
    if (attrs !== undefined && attrs !== null) {
      for (const [key, value] of Object.entries(attrs)) {
        if (value === undefined || value === null || value === false) continue
        if (key === 'class') node.className = value
        else if (key === 'text') node.textContent = String(value)
        else if (key.startsWith('on') && typeof value === 'function') {
          node.addEventListener(key.slice(2).toLowerCase(), value)
        } else if (key === 'value' || key === 'checked' || key === 'disabled' || key === 'type' || key === 'id') {
          node[key] = value
        } else node.setAttribute(key, String(value))
      }
    }
    const children = []
    for (let i = 2; i < arguments.length; i++) {
      const child = arguments[i]
      if (child === undefined || child === null || child === false) continue
      if (Array.isArray(child)) children.push(...child.filter((item) => item !== undefined && item !== null && item !== false))
      else children.push(child)
    }
    const hasElement = children.some((child) => typeof child !== 'string' && typeof child !== 'number')
    if (!hasElement) {
      if (children.length > 0) node.textContent = children.join('')
      return node
    }
    for (const child of children) {
      if (typeof child === 'string' || typeof child === 'number') {
        node.append(el('span', { text: String(child) }))
      } else node.append(child)
    }
    return node
  }

  /** Remove every child without touching the parent. */
  function clear(node) {
    if (node !== null && node !== undefined) node.textContent = ''
  }

  /** The message of anything that was thrown. */
  function messageOf(error) {
    if (error === undefined || error === null) return 'unknown error'
    return typeof error.message === 'string' ? error.message : String(error)
  }

  /** Two-digit clock component. */
  function pad2(value) {
    return String(value).padStart(2, '0')
  }

  /** mm:ss from a millisecond span. */
  function fmtClock(ms) {
    const total = Math.max(0, Math.floor(ms / 1000))
    return pad2(Math.floor(total / 60)) + ':' + pad2(total % 60)
  }

  /** A plausible token count for the status bar. */
  function fmtTokens(chars) {
    const tokens = Math.round(chars / 1.6)
    return tokens >= 1000 ? (tokens / 1000).toFixed(1) + 'k' : String(tokens)
  }

  // --------------------------------------------------------------- network
  const api = {
    async request(path, options) {
      const res = await fetch(path, options)
      let data = null
      try {
        data = await res.json()
      } catch { /* non-JSON error body */ }
      if (data === null || data.ok !== true) {
        const detail = data !== null && data.error !== undefined && data.error !== null
          ? data.error.message
          : 'HTTP ' + res.status
        throw new Error(String(detail))
      }
      return data.value
    },
    post(path, body) {
      return api.request(path, {
        method: 'POST',
        headers: { 'content-type': 'application/json' },
        body: JSON.stringify(body),
      })
    },
    state() { return api.request(ROUTE_PREFIX + '/state') },
    plan(bookId, chapterIndex) {
      return api.request(ROUTE_PREFIX + '/books/' + encodeURIComponent(bookId) + '/plan?chapter=' + chapterIndex)
    },
    settings(patch) { return api.post(ROUTE_PREFIX + '/settings', patch) },
    progress(payload) { return api.post(ROUTE_PREFIX + '/progress', payload) },
    remove(bookId) { return api.post(ROUTE_PREFIX + '/books/' + encodeURIComponent(bookId) + '/delete', {}) },
    upload(name, data) { return api.post(ROUTE_PREFIX + '/import', { name, data }) },
  }

  // ---------------------------------------------------------------- styles
  // Every colour is a shell theme token with a hard fallback, and the fallbacks
  // are re-declared under prefers-color-scheme: dark. A shell that ships the
  // tokens wins; a shell that does not still looks right in both modes.
  const STYLES = `
.dsh-lr-view, .dsh-lr-modal-backdrop {
  --lr-bg: var(--dsw-alias-bg-base, #ffffff);
  --lr-surface: var(--dsw-alias-bg-layer-1, #ffffff);
  --lr-surface-2: var(--dsw-alias-bg-layer-2, #f5f6f7);
  --lr-border: var(--dsw-alias-border-l1, rgba(0,0,0,.04));
  --lr-border-2: var(--dsw-alias-border-l2, rgba(0,0,0,.1));
  --lr-text: var(--dsw-alias-label-primary, #0f1115);
  --lr-text-2: var(--dsw-alias-label-secondary, #61666b);
  --lr-text-3: var(--dsw-alias-label-tertiary, #81858c);
  --lr-hover: var(--dsw-alias-interactive-bg-hover, rgba(38,49,72,.06));
  --lr-accent: var(--dsw-static-blue-500, #3b82f6);
  --lr-ok: var(--dsw-alias-state-success-primary, #22c55e);
  --lr-err: var(--dsw-alias-state-error-primary, #ec1313);
  --lr-warn: var(--dsw-alias-state-warn-primary, #f59e0b);
  --lr-code: var(--dsw-alias-markdown-code-block, #f9fafb);
  --lr-shadow: var(--dsw-shadow-lv3, 0 12px 32px rgba(0,0,0,.12));
  --lr-mono: var(--ds-font-family-code, ui-monospace, SFMono-Regular, Menlo, Consolas, "Liberation Mono", monospace);
}
@media (prefers-color-scheme: dark) {
  .dsh-lr-view, .dsh-lr-modal-backdrop {
    --lr-bg: var(--dsw-alias-bg-base, #151517);
    --lr-surface: var(--dsw-alias-bg-layer-1, #232324);
    --lr-surface-2: var(--dsw-alias-bg-layer-2, #2c2c2e);
    --lr-border: var(--dsw-alias-border-l1, rgba(255,255,255,.06));
    --lr-border-2: var(--dsw-alias-border-l2, rgba(255,255,255,.12));
    --lr-text: var(--dsw-alias-label-primary, #f9fafb);
    --lr-text-2: var(--dsw-alias-label-secondary, #cfd3d6);
    --lr-text-3: var(--dsw-alias-label-tertiary, #adb2b8);
    --lr-hover: var(--dsw-alias-interactive-bg-hover, rgba(255,255,255,.08));
    --lr-code: var(--dsw-alias-markdown-code-block, #1b1b1c);
    --lr-err: var(--dsw-alias-state-error-primary, #f25a5a);
  }
}

/* Sidebar entry (sits with the other plugin entries under the New Session row). */
.dsh-lr-entry {
  display: flex; align-items: center; gap: 8px; position: relative;
  width: calc(100% - 8px); margin: 2px 4px; padding: 6px 10px;
  border: none; border-radius: 8px; background: transparent;
  color: var(--dsw-alias-label-secondary, inherit); font: inherit; font-size: 13px;
  cursor: pointer; text-align: left; box-sizing: border-box;
}
.dsh-lr-entry:hover { background: var(--dsw-alias-interactive-bg-hover, rgba(128,128,128,.12)); color: var(--dsw-alias-label-primary, inherit); }
.dsh-lr-entry[data-active="true"] { background: var(--dsw-alias-interactive-bg-hover, rgba(128,128,128,.18)); color: var(--dsw-alias-label-primary, inherit); font-weight: 500; }
.dsh-lr-entry-icon { display: inline-flex; flex: none; }
.dsh-lr-entry-stats { margin-left: auto; font-size: 11px; line-height: 1; color: var(--dsw-alias-label-tertiary, gray); font-variant-numeric: tabular-nums; white-space: nowrap; }
/* The panel itself: it replaces the conversation column's own children while
   open, rather than floating over them — no dependency on the column being a
   positioned ancestor, which differs between DSH layouts. */
html[data-dsh-lr-open] [data-pane="conversation"] > *:not([data-dsh-lr-view]),
html[data-dsh-lr-open] [class*="centerCol"] > *:not([data-dsh-lr-view]),
html[data-dsh-lr-open] .dshDesktopConversationSurface > *:not([data-dsh-lr-view]) { display: none !important; }
.dsh-lr-view { display: none; background: var(--lr-bg); color: var(--lr-text); }
html[data-dsh-lr-open] .dsh-lr-view {
  display: flex; flex-direction: column; flex: 1 1 auto;
  height: 100%; min-height: 0; overflow: hidden;
}
.dsh-lr-head {
  flex: none; display: flex; align-items: center; gap: 10px;
  padding: 10px 16px; border-bottom: 1px solid var(--lr-border); min-height: 44px; box-sizing: border-box;
}
.dsh-lr-head-title { font-size: 13px; font-weight: 500; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }
.dsh-lr-head-sub { font-size: 12px; color: var(--lr-text-3); white-space: nowrap; }
.dsh-lr-spacer { flex: 1 1 auto; }
.dsh-lr-btn {
  display: inline-flex; align-items: center; gap: 6px; padding: 4px 10px;
  border: 1px solid var(--lr-border-2); border-radius: 7px; background: transparent;
  color: var(--lr-text-2); font: inherit; font-size: 12px; cursor: pointer; white-space: nowrap;
}
.dsh-lr-btn:hover:not(:disabled) { background: var(--lr-hover); color: var(--lr-text); }
.dsh-lr-btn:disabled { opacity: .5; cursor: default; }
.dsh-lr-btn[data-kind="primary"] { background: var(--lr-text); color: var(--lr-bg); border-color: transparent; }
.dsh-lr-btn[data-kind="ghost"] { border-color: transparent; }
.dsh-lr-btn[data-kind="danger"] { color: var(--lr-err); }

/* Transcript. */
.dsh-lr-scroll { flex: 1 1 auto; overflow-y: auto; overflow-x: hidden; }
.dsh-lr-stream { max-width: 760px; margin: 0 auto; padding: 20px 24px 28px; box-sizing: border-box; }
.dsh-lr-turn { margin: 0 0 22px; }
.dsh-lr-user {
  margin: 0 0 14px; padding: 10px 14px; border-radius: 12px;
  background: var(--lr-surface-2); color: var(--lr-text);
  font-size: 14px; line-height: 22px; white-space: pre-wrap; word-break: break-word;
}
.dsh-lr-think {
  display: flex; align-items: baseline; gap: 8px; margin: 0 0 10px;
  font-size: 12px; color: var(--lr-text-3); cursor: pointer;
}
.dsh-lr-think-body { margin: -4px 0 12px; padding-left: 18px; font-size: 12px; line-height: 20px; color: var(--lr-text-3); display: none; }
.dsh-lr-think[data-open="true"] + .dsh-lr-think-body { display: block; }
.dsh-lr-prose { font-size: calc(16px * var(--lr-scale, 1)); line-height: 1.85; color: var(--lr-text); word-break: break-word; }
.dsh-lr-p { margin: 0 0 16px; white-space: pre-wrap; }
.dsh-lr-p:last-child { margin-bottom: 0; }
.dsh-lr-caret::after {
  content: ""; display: inline-block; width: 7px; height: 1.05em; margin-left: 2px;
  vertical-align: text-bottom; background: var(--lr-text); animation: dsh-lr-blink 1s steps(2, start) infinite;
}
@keyframes dsh-lr-blink { to { visibility: hidden; } }
/* Tool rows. */
.dsh-lr-call { margin: 0 0 8px; font-size: 13px; }
.dsh-lr-call-head {
  display: flex; align-items: baseline; gap: 8px; padding: 3px 0;
  cursor: pointer; color: var(--lr-text-2); line-height: 20px;
}
.dsh-lr-call-head:hover { color: var(--lr-text); }
.dsh-lr-dot { flex: none; width: 14px; text-align: center; color: var(--lr-text-3); font-size: 12px; }
.dsh-lr-call[data-status="run"] .dsh-lr-dot { color: var(--lr-warn); animation: dsh-lr-pulse 1.1s ease-in-out infinite; }
.dsh-lr-call[data-status="ok"] .dsh-lr-dot { color: var(--lr-ok); }
@keyframes dsh-lr-pulse { 50% { opacity: .35; } }
.dsh-lr-call-name { font-family: var(--lr-mono); font-size: 12.5px; color: var(--lr-text); }
.dsh-lr-call-arg {
  font-family: var(--lr-mono); font-size: 12.5px; color: var(--lr-text-3);
  overflow: hidden; text-overflow: ellipsis; white-space: nowrap; max-width: 42ch;
}
.dsh-lr-call-tail { margin-left: auto; flex: none; font-size: 11px; color: var(--lr-text-3); font-variant-numeric: tabular-nums; }
.dsh-lr-call-result {
  margin: 0 0 2px 22px; font-family: var(--lr-mono); font-size: 12px; line-height: 18px;
  color: var(--lr-text-3); white-space: nowrap; overflow: hidden; text-overflow: ellipsis;
}
.dsh-lr-call-body {
  display: none; margin: 4px 0 6px 22px; padding: 8px 10px; border-radius: 8px;
  background: var(--lr-code); border: 1px solid var(--lr-border);
  font-family: var(--lr-mono); font-size: 12px; line-height: 19px; color: var(--lr-text-2);
  white-space: pre-wrap; word-break: break-all;
}
.dsh-lr-call[data-open="true"] .dsh-lr-call-body { display: block; }
.dsh-lr-divider {
  display: flex; align-items: center; gap: 10px; margin: 4px 0 20px;
  font-size: 11px; color: var(--lr-text-3);
}
.dsh-lr-divider::before, .dsh-lr-divider::after { content: ""; flex: 1 1 auto; height: 1px; background: var(--lr-border-2); }
.dsh-lr-empty { padding: 48px 24px; text-align: center; color: var(--lr-text-3); font-size: 13px; line-height: 22px; }

/* Composer. */
.dsh-lr-foot { flex: none; padding: 0 24px 14px; }
.dsh-lr-composer {
  max-width: 760px; margin: 0 auto; border: 1px solid var(--lr-border-2); border-radius: 14px;
  background: var(--lr-surface); padding: 8px 8px 6px; box-sizing: border-box;
}
.dsh-lr-input {
  display: block; width: 100%; min-height: 24px; max-height: 120px; padding: 4px 6px;
  border: none; outline: none; resize: none; background: transparent; box-sizing: border-box;
  color: var(--lr-text); font: inherit; font-size: 14px; line-height: 22px;
}
.dsh-lr-composer-row { display: flex; align-items: center; gap: 8px; padding: 2px 4px 0; }
.dsh-lr-hint { font-size: 11px; color: var(--lr-text-3); white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }
/* Modal (library / chapters / settings). */
.dsh-lr-modal-backdrop {
  position: fixed; inset: 0; z-index: 40; display: flex; align-items: center; justify-content: center;
  background: rgba(0,0,0,.42); padding: 24px; box-sizing: border-box;
}
.dsh-lr-modal {
  width: min(680px, 100%); max-height: min(76vh, 720px); display: flex; flex-direction: column;
  background: var(--lr-surface); color: var(--lr-text); border: 1px solid var(--lr-border-2);
  border-radius: 14px; box-shadow: var(--lr-shadow); overflow: hidden;
}
.dsh-lr-modal-head { flex: none; display: flex; align-items: center; gap: 10px; padding: 12px 16px; border-bottom: 1px solid var(--lr-border); font-size: 14px; font-weight: 500; }
.dsh-lr-modal-body { flex: 1 1 auto; overflow-y: auto; padding: 12px 16px; }
.dsh-lr-modal-foot { flex: none; display: flex; align-items: center; gap: 8px; padding: 10px 16px; border-top: 1px solid var(--lr-border); }
.dsh-lr-row {
  display: flex; align-items: center; gap: 10px; padding: 9px 10px; border-radius: 9px;
  cursor: pointer; font-size: 13px; line-height: 20px;
}
.dsh-lr-row:hover { background: var(--lr-hover); }
.dsh-lr-row[data-active="true"] { background: var(--lr-hover); }
.dsh-lr-row-main { flex: 1 1 auto; min-width: 0; }
.dsh-lr-row-title { white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }
.dsh-lr-row-meta { font-size: 11px; color: var(--lr-text-3); white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }
.dsh-lr-field { display: flex; align-items: center; gap: 10px; padding: 7px 0; font-size: 13px; }
.dsh-lr-field-label { flex: none; width: 92px; color: var(--lr-text-2); }
.dsh-lr-field-hint { font-size: 11px; color: var(--lr-text-3); }
.dsh-lr-select, .dsh-lr-number {
  padding: 4px 8px; border: 1px solid var(--lr-border-2); border-radius: 7px;
  background: var(--lr-bg); color: var(--lr-text); font: inherit; font-size: 12px;
}
.dsh-lr-number { width: 78px; }
.dsh-lr-range { flex: 1 1 auto; accent-color: var(--lr-accent); }
.dsh-lr-drop {
  margin: 6px 0 0; padding: 18px; border: 1px dashed var(--lr-border-2); border-radius: 10px;
  text-align: center; font-size: 12px; color: var(--lr-text-3);
}
.dsh-lr-drop[data-over="true"] { border-color: var(--lr-accent); color: var(--lr-text-2); }
.dsh-lr-toast-wrap { position: fixed; left: 50%; bottom: 26px; transform: translateX(-50%); z-index: 60; display: flex; flex-direction: column; gap: 8px; align-items: center; }
.dsh-lr-toast {
  padding: 7px 14px; border-radius: 999px; background: var(--dsw-alias-label-primary, #0f1115);
  color: var(--dsw-alias-bg-base, #fff); font-size: 12px; box-shadow: var(--lr-shadow); max-width: 70vw;
}
.dsh-lr-toast[data-kind="error"] { background: var(--lr-err); color: #fff; }
[data-sidebar-collapsed] .dsh-lr-entry { justify-content: center; }
[data-sidebar-collapsed] .dsh-lr-entry-label, [data-sidebar-collapsed] .dsh-lr-entry-stats { display: none; }
`

  // ----------------------------------------------------------------- model
  const model = {
    open: false,
    hydrated: false,
    books: [],
    progress: {},
    settings: {
      speed: 36, turnChars: 420, toolDensity: 'medium', persona: 'refactor',
      useRealPaths: true, showThinking: true, autoPlay: true, fontScale: 100,
    },
    bookId: null,
    plan: null,
    /** Index of the next turn to play. */
    turnIndex: 0,
    playing: false,
    /** Characters of prose revealed this session, for the fake token counter. */
    charsRead: 0,
    startedAt: 0,
    error: null,
  }

  /** The book record currently open. */
  function currentBook() {
    return model.books.find((book) => book.id === model.bookId)
  }

  /** The chapter list of the open book (never undefined). */
  function chapters() {
    const book = currentBook()
    return book === undefined ? [] : book.chapters
  }

  /** Where the reader is, per the ledger. */
  function savedProgress(bookId) {
    const entry = model.progress[bookId]
    return entry === undefined || entry === null ? { chapterIndex: 0, turnIndex: 0 } : entry
  }

  /** Total prose characters of the open book. */
  function readingRatio() {
    const book = currentBook()
    if (book === undefined || model.plan === null) return 0
    const chapterCount = Math.max(1, book.chapters.length)
    const withinChapter = model.plan.turnCount > 0 ? model.turnIndex / model.plan.turnCount : 0
    return Math.min(1, (model.plan.chapterIndex + withinChapter) / chapterCount)
  }

  // ------------------------------------------------------------- timers
  // Every timer and every in-flight playback carries the run token it was
  // started under. Changing chapter, closing the panel or disposing bumps the
  // token, so anything still queued becomes a no-op instead of typing prose into
  // a detached node.
  const timers = new Set()
  /** Timers that outlive a run (toast dismissal, progress debounce). */
  const chores = new Set()
  let runToken = 0

  function bumpToken() {
    runToken += 1
    for (const id of timers) clearTimeout(id)
    timers.clear()
    return runToken
  }

  function sleep(ms) {
    return new Promise((resolve) => {
      const id = setTimeout(() => {
        timers.delete(id)
        resolve()
      }, ms)
      timers.add(id)
    })
  }

  function nextFrame() {
    return new Promise((resolve) => {
      if (typeof window.requestAnimationFrame === 'function') window.requestAnimationFrame(() => resolve())
      else {
        const id = setTimeout(() => {
          timers.delete(id)
          resolve()
        }, 16)
        timers.add(id)
      }
    })
  }

  // -------------------------------------------------------------- toasts
  let toastWrap = null

  function toast(message, kind) {
    try {
      if (toastWrap === null || !toastWrap.isConnected) {
        toastWrap = el('div', { class: 'dsh-lr-toast-wrap' })
        const root = document.body ?? document.documentElement
        root.append(toastWrap)
      }
      const node = el('div', { class: 'dsh-lr-toast', 'data-kind': kind ?? 'info', text: String(message) })
      toastWrap.append(node)
      const id = setTimeout(() => {
        chores.delete(id)
        try { node.remove() } catch { /* noop */ }
      }, kind === 'error' ? 4200 : 2200)
      chores.add(id)
    } catch (error) {
      console.warn(LOG + ' toast failed:', messageOf(error))
    }
  }

  // ----------------------------------------------------------- dom seats
  let entry = null
  let view = null
  let streamEl = null
  let scrollEl = null
  let headTitleEl = null
  let headSubEl = null
  let inputEl = null
  let sendBtn = null
  let hintEl = null

  function injectStyles() {
    if (document.getElementById(STYLE_ID) !== null) return
    const style = el('style', { id: STYLE_ID, text: STYLES })
    const root = document.head ?? document.documentElement
    root.append(style)
  }

  function sidebarRoot() {
    const column = document.querySelector(SIDEBAR_SELECTOR)
    if (column === null) return undefined
    const logoRow = column.querySelector('[class*="logoRow"]')
    return (logoRow !== null ? logoRow.parentElement : column.firstElementChild) ?? undefined
  }

  function conversationColumn() {
    const column = document.querySelector(CONVERSATION_SELECTOR)
    return column === null ? undefined : column
  }

  function createEntry() {
    const button = el('button', {
      type: 'button', class: 'dsh-lr-entry', 'data-dsh-lr-entry': '', 'aria-label': '长文阅读',
      onClick: () => { setOpen(!model.open) },
    })
    button.append(
      el('span', { class: 'dsh-lr-entry-icon', text: '📄' }),
      el('span', { class: 'dsh-lr-entry-label', text: '长文' }),
      el('span', { class: 'dsh-lr-entry-stats' }),
    )
    return button
  }

  /** Insert the sidebar entry next to the New Session row / the plugin family. */
  function placeEntry() {
    if (entry === null) return false
    const root = sidebarRoot()
    if (root === undefined || !root.isConnected) return false
    if (entry.parentElement === root) return true
    const family = Array.from(root.children).filter((child) =>
      typeof child.matches === 'function' &&
      child.matches(ENTRY_SELECTOR + ', [data-dsh-cgtb-entry], [data-dsh-rp-entry], [data-dsh-taskboard-entry]'))
    if (family.length > 0) {
      root.insertBefore(entry, family[family.length - 1].nextElementSibling ?? null)
      return true
    }
    const nested = root.querySelector('button[class*="newSession"]')
    if (nested !== null && nested.parentElement === root) {
      root.insertBefore(entry, nested.nextElementSibling ?? null)
      return true
    }
    root.append(entry)
    return true
  }

  /** Attach (or re-attach) the panel container as a trailing child of the column. */
  function ensureView() {
    const column = conversationColumn()
    if (column === undefined) return
    if (view === null || !view.isConnected) {
      if (view !== null) view.remove()
      view = el('div', { class: 'dsh-lr-view', 'data-dsh-lr-view': '' })
      streamEl = null
    }
    if (view.parentElement !== column) column.append(view)
  }

  /** Build the panel: a session-shaped header, the transcript, the composer. */
  function buildViewDom() {
    headTitleEl = el('div', { class: 'dsh-lr-head-title', text: '会话' })
    headSubEl = el('div', { class: 'dsh-lr-head-sub' })
    const libBtn = el('button', { class: 'dsh-lr-btn', type: 'button', text: '书架', onClick: () => openLibrary() })
    const tocBtn = el('button', { class: 'dsh-lr-btn', type: 'button', text: '目录', onClick: () => openChapters() })
    const setBtn = el('button', { class: 'dsh-lr-btn', type: 'button', text: '设置', onClick: () => openSettings() })
    const closeBtn = el('button', {
      class: 'dsh-lr-btn', 'data-kind': 'ghost', type: 'button', text: '✕',
      title: '收起（Esc）', onClick: () => setOpen(false),
    })
    const head = el('div', { class: 'dsh-lr-head' },
      headTitleEl, headSubEl, el('div', { class: 'dsh-lr-spacer' }), libBtn, tocBtn, setBtn, closeBtn)

    streamEl = el('div', { class: 'dsh-lr-stream' })
    scrollEl = el('div', { class: 'dsh-lr-scroll' }, streamEl)

    inputEl = el('textarea', { class: 'dsh-lr-input', rows: 1, placeholder: '输入消息…' })
    inputEl.addEventListener('keydown', onComposerKey)
    sendBtn = el('button', {
      class: 'dsh-lr-btn', 'data-kind': 'primary', type: 'button', text: '发送',
      onClick: () => { void submitComposer() },
    })
    hintEl = el('div', { class: 'dsh-lr-hint' })
    const composer = el('div', { class: 'dsh-lr-composer' },
      inputEl,
      el('div', { class: 'dsh-lr-composer-row' }, hintEl, el('div', { class: 'dsh-lr-spacer' }), sendBtn))
    const foot = el('div', { class: 'dsh-lr-foot' }, composer)

    view.append(head, scrollEl, foot)
    bindDropTarget(view)
    renderHead()
  }

  /** Persona labels, mirroring the host's PERSONA_SCRIPTS. */
  const PERSONA_LABELS = { refactor: '重构', debug: '排查', review: '审阅', docs: '文档' }
  const DENSITY_LABELS = { off: '关闭', low: '少', medium: '适中', high: '多' }

  /**
   * The header is the camouflage: a work-shaped session title on the left, and
   * the reading position on the right where a real session shows its context
   * meter. Nothing on it names a book.
   */
  function renderHead() {
    if (headTitleEl === null) return
    const persona = PERSONA_LABELS[model.settings.persona] ?? '重构'
    const firstCall = model.plan !== null && model.plan.turns.length > 0
      ? (model.plan.turns[0].calls.find((call) => typeof call.summary === 'string' && call.summary.includes('/')) ?? null)
      : null
    const target = firstCall !== null ? String(firstCall.summary).split('/').pop() : 'workspace'
    headTitleEl.textContent = persona + ' · ' + target
    const percent = Math.round(readingRatio() * 100)
    const elapsed = model.startedAt > 0 ? fmtClock(Date.now() - model.startedAt) : '00:00'
    const chapterLabel = model.plan === null
      ? '未打开'
      : (model.plan.chapterIndex + 1) + '/' + Math.max(1, chapters().length)
    headSubEl.textContent = chapterLabel + ' · ' + percent + '% · ' + elapsed +
      ' · ' + fmtTokens(model.charsRead) + ' tokens'
    // The test DOM's style object is a write-swallowing proxy, so guard the call
    // rather than assuming CSSStyleDeclaration.
    if (view !== null && typeof view.style.setProperty === 'function') {
      view.style.setProperty('--lr-scale', String((model.settings.fontScale ?? 100) / 100))
    }
    renderHint()
  }

  function renderHint() {
    if (hintEl === null) return
    if (model.playing) hintEl.textContent = '正在输出 · Enter 跳到本段末尾 · Esc 收起'
    else hintEl.textContent = 'Enter 继续 · /help 看命令 · Esc 收起'
    if (sendBtn !== null) sendBtn.textContent = model.playing ? '跳过' : '发送'
  }

  function renderEntry() {
    if (entry === null) return
    if (model.open) entry.dataset.active = 'true'
    else delete entry.dataset.active
    const stats = entry.querySelector('.dsh-lr-entry-stats')
    if (stats === null) return
    const book = currentBook()
    if (book === undefined || model.plan === null) {
      stats.textContent = model.books.length > 0 ? String(model.books.length) : ''
      return
    }
    stats.textContent = (model.plan.chapterIndex + 1) + '/' + Math.max(1, book.chapters.length)
  }

  // -------------------------------------------------------- open / close
  function setOpen(open) {
    if (model.open === open) return
    model.open = open
    const rootEl = document.documentElement
    if (open) {
      for (const attr of OTHER_OPEN_ATTRS) rootEl.removeAttribute(attr)
      rootEl.setAttribute(OPEN_ATTR, '')
      if (typeof CustomEvent === 'function') {
        document.dispatchEvent(new CustomEvent(ACTIVATE_EVENT, { detail: PANEL_NAME }))
      }
      if (model.startedAt === 0) model.startedAt = Date.now()
      void hydrate()
    } else {
      // Closing is also the panic key: stop typing immediately, leave nothing moving.
      bumpToken()
      model.playing = false
      rootEl.removeAttribute(OPEN_ATTR)
      closeModal()
      renderHint()
    }
    renderEntry()
  }

  // ------------------------------------------------------------ transcript
  /** Scroll the transcript to the bottom, best effort. */
  function stickToBottom() {
    if (scrollEl === null) return
    const height = scrollEl.scrollHeight
    if (typeof height === 'number') scrollEl.scrollTop = height
  }

  function turnNode() {
    const node = el('div', { class: 'dsh-lr-turn' })
    if (streamEl !== null) streamEl.append(node)
    return node
  }

  function userBlock(parent, text) {
    parent.append(el('div', { class: 'dsh-lr-user', text: String(text) }))
  }

  function thinkingBlock(parent, thinking) {
    const head = el('div', { class: 'dsh-lr-think' },
      el('span', { text: '✳' }),
      el('span', { text: '思考 ' + thinking.seconds.toFixed(1) + 's' }))
    const body = el('div', { class: 'dsh-lr-think-body', text: String(thinking.text) })
    head.addEventListener('click', () => {
      if (head.dataset.open === 'true') delete head.dataset.open
      else head.dataset.open = 'true'
    })
    parent.append(head, body)
  }

  /** The expanded body of a tool row: arguments, then the tool's own output. */
  function callBodyText(call) {
    const lines = []
    try {
      lines.push(JSON.stringify(call.args ?? {}, null, 2))
    } catch {
      lines.push('{}')
    }
    if (Array.isArray(call.resultLines) && call.resultLines.length > 0) {
      lines.push('', call.resultLines.join('\n'))
    }
    return lines.join('\n')
  }

  /**
   * One tool row. `settled` renders the finished state directly (instant replay);
   * otherwise the row starts in its running state and `settle()` finishes it.
   */
  function callBlock(parent, call, settled) {
    const wrap = el('div', { class: 'dsh-lr-call', 'data-dsh-lr-call': '', 'data-status': settled ? 'ok' : 'run' })
    const tail = el('span', { class: 'dsh-lr-call-tail', text: settled ? (call.ms / 1000).toFixed(1) + 's' : '运行中' })
    const head = el('div', { class: 'dsh-lr-call-head' },
      el('span', { class: 'dsh-lr-dot', text: '●' }),
      el('span', { class: 'dsh-lr-call-name', text: String(call.name) }),
      el('span', { class: 'dsh-lr-call-arg', text: String(call.summary ?? '') }),
      tail)
    const result = el('div', { class: 'dsh-lr-call-result', text: settled ? String(call.result ?? '') : '' })
    const body = el('div', { class: 'dsh-lr-call-body', text: callBodyText(call) })
    head.addEventListener('click', () => {
      if (wrap.dataset.open === 'true') delete wrap.dataset.open
      else wrap.dataset.open = 'true'
    })
    wrap.append(head, result, body)
    parent.append(wrap)
    return {
      settle() {
        wrap.dataset.status = 'ok'
        tail.textContent = (call.ms / 1000).toFixed(1) + 's'
        result.textContent = String(call.result ?? '')
      },
    }
  }

  function divider(text) {
    if (streamEl === null) return
    streamEl.append(el('div', { class: 'dsh-lr-divider', text: String(text) }))
  }

  // ---------------------------------------------------------------- playback
  /** Set while a turn is streaming and the reader asked to jump to its end. */
  let skipRequested = false

  /** Speed at or above this reveals the paragraph at once. */
  const INSTANT_SPEED = 600

  /** Keep the transcript bounded; a 200-turn chapter must not build 200 turns of DOM. */
  const MAX_TURN_NODES = 24

  function trimTranscript() {
    if (streamEl === null) return
    while (streamEl.children.length > MAX_TURN_NODES) {
      const first = streamEl.children[0]
      if (first === undefined) break
      first.remove()
    }
  }

  /** Type `text` into `node`, one frame at a time. Returns false when preempted. */
  async function typeInto(node, text, token) {
    const speed = Math.max(6, Number(model.settings.speed) || 36)
    if (speed >= INSTANT_SPEED) {
      node.textContent = text
      return true
    }
    node.classList.add('dsh-lr-caret')
    let shown = 0
    let last = Date.now()
    while (shown < text.length) {
      if (token !== runToken) {
        node.classList.remove('dsh-lr-caret')
        return false
      }
      if (skipRequested) break
      await nextFrame()
      if (token !== runToken) {
        node.classList.remove('dsh-lr-caret')
        return false
      }
      const stamp = Date.now()
      const step = Math.max(1, Math.round(speed * Math.max(1, stamp - last) / 1000))
      last = stamp
      shown = Math.min(text.length, shown + step)
      node.textContent = text.slice(0, shown)
      stickToBottom()
    }
    node.textContent = text
    node.classList.remove('dsh-lr-caret')
    return true
  }

  /** Render one turn with no animation — used when resuming mid-chapter. */
  function renderTurnInstant(turn) {
    const node = turnNode()
    userBlock(node, turn.prompt)
    if (turn.thinking !== null && turn.thinking !== undefined && model.settings.showThinking !== false) {
      thinkingBlock(node, turn.thinking)
    }
    for (const call of turn.calls) callBlock(node, call, true)
    const prose = el('div', { class: 'dsh-lr-prose' })
    node.append(prose)
    for (const paragraph of turn.paragraphs) prose.append(el('div', { class: 'dsh-lr-p', text: paragraph }))
    trimTranscript()
  }

  /** Render one turn the way a session would: tools first, then the reply. */
  async function playTurnAnimated(turn, token, userText) {
    const node = turnNode()
    userBlock(node, userText !== undefined && userText.length > 0 ? userText : turn.prompt)
    stickToBottom()
    await sleep(160)
    if (token !== runToken) return false
    if (turn.thinking !== null && turn.thinking !== undefined && model.settings.showThinking !== false) {
      thinkingBlock(node, turn.thinking)
      stickToBottom()
      await sleep(220)
      if (token !== runToken) return false
    }
    for (const call of turn.calls) {
      const row = callBlock(node, call, false)
      stickToBottom()
      await sleep(Math.min(MAX_CALL_MS, Math.max(120, Number(call.ms) || 200)))
      if (token !== runToken) return false
      row.settle()
    }
    const prose = el('div', { class: 'dsh-lr-prose' })
    node.append(prose)
    for (const paragraph of turn.paragraphs) {
      const line = el('div', { class: 'dsh-lr-p' })
      prose.append(line)
      const done = await typeInto(line, paragraph, token)
      if (!done) return false
    }
    trimTranscript()
    stickToBottom()
    return true
  }

  /** Debounced progress write; the ledger does not need every keystroke. */
  let saveTimer = null

  function scheduleProgressSave() {
    if (model.bookId === null || model.plan === null) return
    if (saveTimer !== null) {
      clearTimeout(saveTimer)
      chores.delete(saveTimer)
    }
    const payload = {
      bookId: model.bookId,
      chapterIndex: model.plan.chapterIndex,
      turnIndex: model.turnIndex,
    }
    saveTimer = setTimeout(() => {
      chores.delete(saveTimer)
      saveTimer = null
      api.progress(payload)
        .then((saved) => { model.progress[payload.bookId] = saved })
        .catch((error) => { console.warn(LOG + ' progress not saved:', messageOf(error)) })
    }, 700)
    chores.add(saveTimer)
  }

  /** Play the next turn, or roll into the next chapter when this one is done. */
  async function advance(userText) {
    if (model.plan === null) {
      toast('先在书架里选一本')
      return
    }
    if (model.playing) {
      skipRequested = true
      return
    }
    const turn = model.plan.turns[model.turnIndex]
    if (turn === undefined) {
      await nextChapter()
      return
    }
    const token = runToken
    model.playing = true
    skipRequested = false
    renderHint()
    let finished = false
    try {
      finished = await playTurnAnimated(turn, token, userText)
    } catch (error) {
      console.warn(LOG + ' playback failed:', messageOf(error))
    } finally {
      if (token === runToken) {
        model.playing = false
        skipRequested = false
        renderHint()
      }
    }
    if (!finished || token !== runToken) return
    model.turnIndex += 1
    model.charsRead += turn.chars
    scheduleProgressSave()
    renderHead()
    renderEntry()
    if (model.settings.autoPlay === false) return
    await sleep(AUTO_GAP_MS)
    if (token === runToken && model.open) void advance()
  }

  /**
   * Load one chapter's plan and reset the transcript.
   * @param options - { resumeTurn, autostart, keep }
   */
  async function loadChapter(index, options) {
    const book = currentBook()
    if (book === undefined) return
    const token = bumpToken()
    model.playing = false
    skipRequested = false
    try {
      const plan = await api.plan(book.id, index)
      if (token !== runToken) return
      model.plan = plan
      model.turnIndex = 0
      // A chapter roll keeps the transcript so the seam reads like one long
      // session; an explicit jump (table of contents, /goto, another book)
      // starts clean. trimTranscript bounds the growth either way.
      if (options?.keep !== true) clear(streamEl)
      const resumeTurn = Math.min(Math.max(0, options?.resumeTurn ?? 0), plan.turns.length)
      if (resumeTurn > 0) {
        const from = Math.max(0, resumeTurn - REPLAY_TURNS)
        if (from > 0) divider('上下文已压缩 · ' + from + ' 轮已折叠')
        for (let i = from; i < resumeTurn; i++) renderTurnInstant(plan.turns[i])
        model.turnIndex = resumeTurn
        model.charsRead += plan.turns.slice(0, resumeTurn).reduce((sum, turn) => sum + turn.chars, 0)
        stickToBottom()
      }
      renderHead()
      renderEntry()
      if (options?.autostart !== false && model.settings.autoPlay !== false) void advance()
    } catch (error) {
      if (token !== runToken) return
      model.error = messageOf(error)
      toast('打开失败：' + model.error, 'error')
      renderEmpty('这一章打不开：' + model.error)
    }
  }

  /** Roll into the next chapter, dressed as a context compaction. */
  async function nextChapter() {
    const book = currentBook()
    if (book === undefined || model.plan === null) return
    const next = model.plan.chapterIndex + 1
    if (next >= book.chapters.length) {
      divider('任务完成 · 无更多输出')
      toast('读完了')
      return
    }
    divider('上下文已压缩 · 继续')
    await loadChapter(next, { resumeTurn: 0, keep: true })
  }

  /** Open a book at its saved position. */
  async function openBook(bookId, options) {
    const book = model.books.find((entry) => entry.id === bookId)
    if (book === undefined) return
    model.bookId = bookId
    model.charsRead = 0
    const saved = savedProgress(bookId)
    const chapterIndex = options?.chapterIndex ?? saved.chapterIndex ?? 0
    const resumeTurn = options?.chapterIndex === undefined ? (saved.turnIndex ?? 0) : 0
    await loadChapter(Math.min(chapterIndex, Math.max(0, book.chapters.length - 1)), {
      resumeTurn,
      autostart: options?.autostart,
    })
  }

  function renderEmpty(message) {
    if (streamEl === null) return
    clear(streamEl)
    streamEl.append(el('div', { class: 'dsh-lr-empty', text: message }))
  }

  /** Load the library once per open, then restore the last position. */
  async function hydrate() {
    if (model.hydrated) {
      renderHead()
      return
    }
    try {
      const state = await api.state()
      model.hydrated = true
      model.books = Array.isArray(state.books) ? state.books : []
      // Copy, don't alias: progress is written back on every finished turn, and
      // mutating a decoded response body is how a cached fixture ends up shared.
      model.progress = { ...(state.progress ?? {}) }
      model.settings = { ...model.settings, ...(state.settings ?? {}) }
      renderHead()
      renderEntry()
      if (model.books.length === 0) {
        renderEmpty('书架是空的。把 .txt 或 .epub 拖到这里，或者点右上角「书架」导入。')
        return
      }
      // Freshest position wins; a first-run reader lands on the bundled sample.
      let pick = model.books[0].id
      let freshest = -1
      for (const [id, entry] of Object.entries(model.progress)) {
        const at = entry?.updatedAt ?? 0
        if (at > freshest && model.books.some((book) => book.id === id)) {
          freshest = at
          pick = id
        }
      }
      await openBook(pick, { autostart: false })
    } catch (error) {
      model.error = messageOf(error)
      renderEmpty('读不到书架：' + model.error)
    }
  }

  // ---------------------------------------------------------------- composer
  const HELP_TEXT = [
    '/lib 书架 · /toc 目录 · /next 下一章 · /prev 上一章 · /goto N 跳章',
    '/speed N 字/秒（600=立即） · /font N 字号% · /persona refactor|debug|review|docs',
    '/density off|low|medium|high · /auto 自动播放开关 · /stop 停',
  ].join('\n')

  /** Apply one settings patch locally and on the host. */
  async function patchSettings(patch, note) {
    model.settings = { ...model.settings, ...patch }
    renderHead()
    try {
      const saved = await api.settings(patch)
      model.settings = { ...model.settings, ...saved }
    } catch (error) {
      toast('设置没保存：' + messageOf(error), 'error')
    }
    renderHead()
    if (note !== undefined) toast(note)
  }

  /** Handle a slash command. Returns true when the text was a command. */
  function runCommand(text) {
    const match = /^\/([a-z一-龥]+)\s*(.*)$/i.exec(text)
    if (match === null) return false
    const name = match[1].toLowerCase()
    const arg = match[2].trim()
    const number = Number.parseInt(arg, 10)
    if (name === 'help' || name === '帮助') { toast(HELP_TEXT); return true }
    if (name === 'lib' || name === '书架') { openLibrary(); return true }
    if (name === 'toc' || name === '目录') { openChapters(); return true }
    if (name === 'set' || name === '设置') { openSettings(); return true }
    if (name === 'next' || name === 'n') { void nextChapter(); return true }
    if (name === 'prev' || name === 'p') {
      const index = model.plan === null ? 0 : model.plan.chapterIndex - 1
      if (index < 0) toast('已经是第一章')
      else void loadChapter(index, { resumeTurn: 0 })
      return true
    }
    if (name === 'goto' || name === 'g') {
      if (!Number.isFinite(number)) toast('用法：/goto 3')
      else void loadChapter(Math.max(0, number - 1), { resumeTurn: 0 })
      return true
    }
    if (name === 'speed') {
      if (Number.isFinite(number)) void patchSettings({ speed: number }, '速度 ' + number + ' 字/秒')
      else toast('用法：/speed 40')
      return true
    }
    if (name === 'font') {
      if (Number.isFinite(number)) void patchSettings({ fontScale: number }, '字号 ' + number + '%')
      else toast('用法：/font 110')
      return true
    }
    if (name === 'persona') { void patchSettings({ persona: arg }, '伪装：' + arg); return true }
    if (name === 'density') { void patchSettings({ toolDensity: arg }, '工具调用：' + arg); return true }
    if (name === 'auto') {
      void patchSettings({ autoPlay: model.settings.autoPlay === false }, model.settings.autoPlay === false ? '自动播放已开' : '自动播放已关')
      return true
    }
    if (name === 'stop') { bumpToken(); model.playing = false; renderHint(); return true }
    toast('没有这个命令：/' + name)
    return true
  }

  /**
   * Sending is how reading advances — which is the point: to anyone watching,
   * the reader is prompting an agent. Whatever they typed becomes the user
   * message of the next turn, so the transcript reads like their own words.
   */
  async function submitComposer() {
    const raw = inputEl === null ? '' : String(inputEl.value ?? '')
    const text = raw.trim()
    if (text.startsWith('/')) {
      if (inputEl !== null) inputEl.value = ''
      runCommand(text)
      return
    }
    if (model.playing) {
      skipRequested = true
      renderHint()
      return
    }
    if (inputEl !== null) inputEl.value = ''
    await advance(text.length > 0 ? text : undefined)
  }

  function onComposerKey(event) {
    if (event.key === 'Enter' && event.shiftKey !== true) {
      event.preventDefault()
      void submitComposer()
      return
    }
    if (event.key === 'Escape') {
      event.preventDefault()
      setOpen(false)
    }
  }

  // ------------------------------------------------------------------ modal
  let modal = null

  function closeModal() {
    if (modal !== null) {
      try { modal.remove() } catch { /* noop */ }
      modal = null
    }
  }

  /** Open a modal frame; returns its body and footer for the caller to fill. */
  function openModal(title) {
    closeModal()
    const body = el('div', { class: 'dsh-lr-modal-body' })
    const foot = el('div', { class: 'dsh-lr-modal-foot' })
    const closeBtn = el('button', { class: 'dsh-lr-btn', 'data-kind': 'ghost', type: 'button', text: '✕', onClick: () => closeModal() })
    const frame = el('div', { class: 'dsh-lr-modal' },
      el('div', { class: 'dsh-lr-modal-head' }, el('span', { text: title }), el('div', { class: 'dsh-lr-spacer' }), closeBtn),
      body, foot)
    const backdrop = el('div', { class: 'dsh-lr-modal-backdrop', 'data-dsh-lr-modal': '' }, frame)
    backdrop.addEventListener('click', (event) => {
      if (event.target === backdrop) closeModal()
    })
    const root = document.body ?? document.documentElement
    root.append(backdrop)
    modal = backdrop
    return { body, foot, close: closeModal }
  }

  // ---------------------------------------------------------------- library
  /** Human-readable size of a book. */
  function fmtChars(chars) {
    return chars >= 10000 ? (chars / 10000).toFixed(1) + ' 万字' : chars + ' 字'
  }

  function openLibrary() {
    const frame = openModal('书架')
    const list = el('div', {})

    const redraw = () => {
      clear(list)
      if (model.books.length === 0) {
        list.append(el('div', { class: 'dsh-lr-empty', text: '还没有书。导入一个 .txt 或 .epub。' }))
        return
      }
      for (const book of model.books) {
        const saved = savedProgress(book.id)
        const where = (saved.chapterIndex ?? 0) + 1
        const meta = [
          book.format.toUpperCase(),
          fmtChars(book.chars),
          book.chapters.length + ' 章',
          '读到第 ' + where + ' 章',
          book.author.length > 0 ? book.author : null,
        ].filter((part) => part !== null).join(' · ')
        const del = el('button', {
          class: 'dsh-lr-btn', 'data-kind': 'danger', type: 'button', text: '删除',
          onClick: (event) => {
            event.stopPropagation()
            void removeBook(book, redraw)
          },
        })
        const row = el('div', {
          class: 'dsh-lr-row', 'data-active': book.id === model.bookId ? 'true' : null,
          onClick: () => {
            closeModal()
            void openBook(book.id)
          },
        },
        el('div', { class: 'dsh-lr-row-main' },
          el('div', { class: 'dsh-lr-row-title', text: book.title }),
          el('div', { class: 'dsh-lr-row-meta', text: meta })),
        del)
        list.append(row)
      }
    }
    redraw()

    const drop = el('div', { class: 'dsh-lr-drop', text: '把 .txt / .epub 拖到这里，或点下面的按钮选文件' })
    bindDropTarget(drop, drop)
    frame.body.append(list, drop)
    const importBtn = el('button', {
      class: 'dsh-lr-btn', 'data-kind': 'primary', type: 'button', text: '导入文件…',
      onClick: () => pickFile(),
    })
    frame.foot.append(importBtn, el('div', { class: 'dsh-lr-spacer' }),
      el('div', { class: 'dsh-lr-field-hint', text: 'txt 支持 UTF-8 / GB18030；epub 取 spine 顺序' }))
  }

  async function removeBook(book, redraw) {
    if (typeof window.confirm === 'function' && !window.confirm('删除《' + book.title + '》？')) return
    try {
      await api.remove(book.id)
      model.books = model.books.filter((entry) => entry.id !== book.id)
      delete model.progress[book.id]
      if (model.bookId === book.id) {
        bumpToken()
        model.bookId = null
        model.plan = null
        renderEmpty('这本已经删了。换一本吧。')
      }
      renderEntry()
      redraw()
      toast('已删除')
    } catch (error) {
      toast('删除失败：' + messageOf(error), 'error')
    }
  }

  // ----------------------------------------------------------------- import
  /** Open the OS file picker. */
  function pickFile() {
    const input = el('input', { type: 'file', accept: '.txt,.epub' })
    input.addEventListener('change', () => {
      const files = input.files
      const file = files !== undefined && files !== null ? files[0] : undefined
      if (file !== undefined) void uploadFile(file)
    })
    if (typeof input.click === 'function') input.click()
  }

  /**
   * Upload one file as base64. FileReader's data URL is used rather than btoa so
   * a GB18030 .txt survives the trip: the bytes are never decoded in the browser,
   * only on the host, which knows how to sniff the encoding.
   */
  async function uploadFile(file) {
    const Reader = window.FileReader
    if (typeof Reader !== 'function') {
      toast('这个环境读不了本地文件', 'error')
      return
    }
    toast('正在导入 ' + String(file.name ?? '文件') + '…')
    try {
      const data = await new Promise((resolve, reject) => {
        const reader = new Reader()
        reader.onload = () => {
          const result = String(reader.result ?? '')
          const comma = result.indexOf(',')
          resolve(comma >= 0 ? result.slice(comma + 1) : '')
        }
        reader.onerror = () => reject(new Error('读文件失败'))
        reader.readAsDataURL(file)
      })
      const summary = await api.upload(file.name, data)
      model.books = [summary, ...model.books.filter((book) => book.id !== summary.id)]
      closeModal()
      renderEntry()
      await openBook(summary.id, { chapterIndex: 0 })
      toast('已导入《' + summary.title + '》· ' + summary.chapters.length + ' 章')
    } catch (error) {
      toast('导入失败：' + messageOf(error), 'error')
    }
  }

  /** Accept dropped files anywhere on `node`. */
  function bindDropTarget(node, highlight) {
    if (node === null || node === undefined) return
    const mark = highlight ?? null
    node.addEventListener('dragover', (event) => {
      if (typeof event.preventDefault === 'function') event.preventDefault()
      if (mark !== null) mark.dataset.over = 'true'
    })
    node.addEventListener('dragleave', () => {
      if (mark !== null) delete mark.dataset.over
    })
    node.addEventListener('drop', (event) => {
      if (typeof event.preventDefault === 'function') event.preventDefault()
      if (mark !== null) delete mark.dataset.over
      const transfer = event.dataTransfer
      const files = transfer === undefined || transfer === null ? null : transfer.files
      if (files === null || files === undefined || files.length === 0) return
      void uploadFile(files[0])
    })
  }

  // --------------------------------------------------------------- chapters
  function openChapters() {
    const book = currentBook()
    if (book === undefined) {
      toast('先在书架里选一本')
      return
    }
    const frame = openModal('目录 · ' + book.title)
    const here = model.plan === null ? -1 : model.plan.chapterIndex
    for (const chapter of book.chapters) {
      frame.body.append(el('div', {
        class: 'dsh-lr-row', 'data-active': chapter.index === here ? 'true' : null,
        onClick: () => {
          closeModal()
          void loadChapter(chapter.index, { resumeTurn: 0 })
        },
      },
      el('div', { class: 'dsh-lr-row-main' },
        el('div', { class: 'dsh-lr-row-title', text: chapter.title }),
        el('div', { class: 'dsh-lr-row-meta', text: fmtChars(chapter.chars) })),
      el('div', { class: 'dsh-lr-row-meta', text: '#' + (chapter.index + 1) })))
    }
    frame.foot.append(el('div', { class: 'dsh-lr-field-hint', text: '共 ' + book.chapters.length + ' 章 · ' + fmtChars(book.chars) }))
  }

  // --------------------------------------------------------------- settings
  /** One labelled settings row. */
  function field(label, control, hint) {
    return el('div', { class: 'dsh-lr-field' },
      el('div', { class: 'dsh-lr-field-label', text: label }),
      control,
      hint === undefined ? null : el('div', { class: 'dsh-lr-field-hint', text: hint }))
  }

  function select(options, value, onChange) {
    const node = el('select', { class: 'dsh-lr-select' })
    for (const [key, label] of options) {
      const option = el('option', { value: key, text: label })
      if (key === value) option.setAttribute('selected', 'selected')
      node.append(option)
    }
    node.value = value
    node.addEventListener('change', () => onChange(node.value))
    return node
  }

  function toggle(value, onChange) {
    const node = el('input', { type: 'checkbox' })
    node.checked = value !== false
    node.addEventListener('change', () => onChange(node.checked === true))
    return node
  }

  function openSettings() {
    const frame = openModal('阅读设置')
    const settings = model.settings

    const speed = el('input', { class: 'dsh-lr-number', type: 'number', min: 6, max: 600, value: settings.speed })
    const speedHint = el('div', { class: 'dsh-lr-field-hint', text: settings.speed >= INSTANT_SPEED ? '立即显示' : '字 / 秒' })
    speed.addEventListener('change', () => {
      const value = Number.parseInt(String(speed.value), 10)
      if (!Number.isFinite(value)) return
      speedHint.textContent = value >= INSTANT_SPEED ? '立即显示' : '字 / 秒'
      void patchSettings({ speed: value })
    })

    const turn = el('input', { class: 'dsh-lr-number', type: 'number', min: 120, max: 2400, value: settings.turnChars })
    turn.addEventListener('change', () => {
      const value = Number.parseInt(String(turn.value), 10)
      if (Number.isFinite(value)) void patchSettings({ turnChars: value }, '下一章生效')
    })

    const font = el('input', { class: 'dsh-lr-number', type: 'number', min: 80, max: 160, value: settings.fontScale })
    font.addEventListener('change', () => {
      const value = Number.parseInt(String(font.value), 10)
      if (Number.isFinite(value)) void patchSettings({ fontScale: value })
    })

    frame.body.append(
      field('速度', speed, undefined),
      el('div', { class: 'dsh-lr-field' }, el('div', { class: 'dsh-lr-field-label' }), speedHint),
      field('每轮字数', turn, '决定一次「回复」多长'),
      field('字号', font, '%'),
      field('伪装', select(Object.entries(PERSONA_LABELS), settings.persona, (value) => {
        void patchSettings({ persona: value }, '下一章生效')
      }), '装作在做什么'),
      field('工具调用', select(Object.entries(DENSITY_LABELS), settings.toolDensity, (value) => {
        void patchSettings({ toolDensity: value }, '下一章生效')
      }), '每轮插几条'),
      field('思考块', toggle(settings.showThinking, (value) => { void patchSettings({ showThinking: value }) }), '显示「思考 3.4s」'),
      field('自动播放', toggle(settings.autoPlay, (value) => { void patchSettings({ autoPlay: value }) }), '关掉就一轮一轮按'),
      field('真实路径', toggle(settings.useRealPaths, (value) => {
        void patchSettings({ useRealPaths: value }, '下一章生效')
      }), '工具调用引用工作区里真实存在的文件'),
    )
    frame.foot.append(el('div', { class: 'dsh-lr-field-hint', text: 'Esc 收起面板 · 「下一章生效」的项会在切章后应用' }))
  }

  // ---------------------------------------------------------------- keyboard
  /** True when the event came from somewhere that owns its own keys. */
  function inTextField(target) {
    if (target === null || target === undefined) return false
    const tag = typeof target.tagName === 'string' ? target.tagName : ''
    if (tag === 'TEXTAREA' || tag === 'INPUT' || tag === 'SELECT') return true
    if (typeof target.closest !== 'function') return false
    return target.closest('[data-dsh-lr-modal]') !== null
  }

  function onKeyDown(event) {
    if (!model.open) return
    if (event.key === 'Escape') {
      // The panic key. It works from anywhere, including the composer.
      if (modal !== null) closeModal()
      else setOpen(false)
      return
    }
    if (inTextField(event.target)) return
    if (event.key === ' ' || event.key === 'Enter' || event.key === 'ArrowRight') {
      if (typeof event.preventDefault === 'function') event.preventDefault()
      void advance()
      return
    }
    if (event.key === ']') {
      if (typeof event.preventDefault === 'function') event.preventDefault()
      void nextChapter()
      return
    }
    if (event.key === '[') {
      if (typeof event.preventDefault === 'function') event.preventDefault()
      const index = model.plan === null ? 0 : model.plan.chapterIndex - 1
      if (index < 0) toast('已经是第一章')
      else void loadChapter(index, { resumeTurn: 0 })
    }
  }

  // ------------------------------------------------------------------- boot
  const bootState = { running: false }

  /** DSH web-shell entry: mount the sidebar entry + the reading panel. */
  function apply(ctx) {
    if (typeof window === 'undefined' || typeof document === 'undefined') return
    if (bootState.running) return
    bootState.running = true
    const state = { disposed: false }
    let observer = null
    let timer = null
    let onActivate = null
    let onDocClick = null
    let onKeys = null

    function ensureMounted() {
      if (state.disposed) return
      try {
        if (entry === null) entry = createEntry()
        placeEntry()
        renderEntry()
        if (conversationColumn() !== undefined) {
          ensureView()
          if (view !== null && view.firstElementChild === null) buildViewDom()
        }
      } catch (error) {
        console.warn(LOG + ' seat mount failed:', messageOf(error))
      }
    }

    function dispose() {
      if (state.disposed) return
      state.disposed = true
      bumpToken()
      for (const id of chores) clearTimeout(id)
      chores.clear()
      if (timer !== null) clearInterval(timer)
      if (observer !== null) { try { observer.disconnect() } catch { /* noop */ } }
      if (onActivate !== null) document.removeEventListener(ACTIVATE_EVENT, onActivate)
      if (onDocClick !== null) document.removeEventListener('click', onDocClick, true)
      if (onKeys !== null) document.removeEventListener('keydown', onKeys, true)
      document.documentElement.removeAttribute(OPEN_ATTR)
      closeModal()
      model.open = false
      model.playing = false
      model.hydrated = false
      model.plan = null
      if (entry !== null) { try { entry.remove() } catch { /* noop */ } entry = null }
      if (view !== null) { try { view.remove() } catch { /* noop */ } view = null }
      if (toastWrap !== null) { try { toastWrap.remove() } catch { /* noop */ } toastWrap = null }
      streamEl = null
      const style = document.getElementById(STYLE_ID)
      if (style !== null) style.remove()
      bootState.running = false
    }

    try {
      injectStyles()
      ensureMounted()
      if (typeof MutationObserver === 'function') {
        observer = new MutationObserver(() => { ensureMounted() })
        const root = document.body ?? document.documentElement
        observer.observe(root, { childList: true, subtree: true })
      }
      timer = setInterval(() => {
        ensureMounted()
        // Also keeps the header's clock moving while a chapter is open.
        if (model.open) renderHead()
      }, 3000)

      onActivate = (event) => {
        if (state.disposed) return
        if (event.detail !== undefined && event.detail !== PANEL_NAME && model.open) setOpen(false)
      }
      onDocClick = (event) => {
        if (state.disposed || !model.open) return
        const target = event.target
        if (target === null || target === undefined || typeof target.closest !== 'function') return
        if (target.closest(ENTRY_SELECTOR + ', ' + VIEW_SELECTOR +
          ', [data-dsh-lr-modal], .dsh-lr-toast-wrap') !== null) return
        setOpen(false)
      }
      onKeys = (event) => {
        if (state.disposed) return
        onKeyDown(event)
      }
      document.addEventListener(ACTIVATE_EVENT, onActivate)
      document.addEventListener('click', onDocClick, true)
      document.addEventListener('keydown', onKeys, true)

      if (ctx !== undefined && ctx !== null && typeof ctx.effect === 'function') {
        ctx.effect(() => dispose, PLUGIN_ID + ': client mount')
      } else if (typeof window.addEventListener === 'function') {
        window.addEventListener('beforeunload', dispose, { once: true })
      }
    } catch (error) {
      console.error(LOG + ' client boot failed:', messageOf(error))
      dispose()
    }
  }

  // ---------------------------------------------------------------- export
  // The wrap step evaluates this file inside window.__ModuleLoader__.load with a
  // CommonJS `module` in scope; a plain Node require() gets the same shape.
  if (typeof module !== 'undefined' && module !== null && module.exports !== undefined) {
    module.exports = {
      name: PLUGIN_ID + '/client',
      inject: [],
      apply,
    }
  }
})();
    return module.exports;
  }
});
