/**
 * Wraps src/client/index.js into the DSH browser module-loader shape every
 * published client plugin uses (window.__ModuleLoader__.load), producing the
 * single-file lib/client.js that package.json exports as "./client".
 *
 * The client source is dependency-free vanilla DOM: it never requires
 * anything, so the loader `require` argument is simply unused. The inner IIFE
 * assigns `module.exports` when it sees a CommonJS `module` — exactly what the
 * factory provides — and the factory returns it. Kept ASCII-safe apart from the
 * UI's Chinese labels: the file is LF-only with a single trailing newline, no BOM.
 *
 * @module dsh-plugin-longread/scripts/wrap-client
 */
import { readFile, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { Script } from 'node:vm'

const root = dirname(dirname(fileURLToPath(import.meta.url)))

/** Loader plugin id (matches the package name and the cordis.patch.yml row). */
export const PLUGIN_ID = 'dsh-plugin-longread'

/** Generated-file banner (plain ASCII comment). */
export const GENERATED_HEADER = [
  '/**',
  ' * dsh-plugin-longread client bundle - GENERATED by scripts/wrap-client.mjs.',
  ' * Do not edit; the source of truth is src/client/index.js (npm run build).',
  ' */',
  '',
].join('\n')

/** Wrap one client source file for the DSH module loader. */
export function wrapClient(source) {
  const body = String(source).replace(/\s+$/, '')
  return (
    GENERATED_HEADER +
    'window.__ModuleLoader__.load({\n' +
    `  id: '${PLUGIN_ID}',\n` +
    '  factory: (require) => {\n' +
    '    var module = { exports: {} };\n' +
    '    var exports = module.exports;\n' +
    `${body}\n` +
    '    return module.exports;\n' +
    '  }\n' +
    '});\n'
  )
}

/**
 * The browser loads this file as a CLASSIC SCRIPT, where a surviving `import` or
 * `export` statement is a SyntaxError and the whole bundle silently fails to
 * register. `node --check` (what scripts/check.mjs runs) cannot see it:
 * package.json says `type: module`, so it parses lib/client.js as ESM, where both
 * keywords are perfectly legal. `new Script()` parses in script mode, which is
 * the mode that actually matters.
 *
 * This lives in the build rather than in check.mjs on purpose: `npm pack` runs
 * `prepack` → build, and a tarball is how the bundle reaches a user.
 *
 * @param {string} bundle
 */
export function assertLoadableInBrowser(bundle) {
  try {
    new Script(bundle, { filename: 'lib/client.js' })
  } catch (error) {
    throw new Error(
      `wrap-client produced a bundle the browser cannot parse as a script: ${error.message}`,
    )
  }
  const leftover = bundle
    .split('\n')
    .map((line, index) => ({ line, number: index + 1 }))
    .filter(({ line }) => /^\s*(import\s*[{('"*]|export\s)/.test(line))
  if (leftover.length > 0) {
    const where = leftover.map(({ number, line }) => `  ${number}: ${line.trim()}`).join('\n')
    throw new Error(`wrap-client left ${leftover.length} module statement(s) in the bundle:\n${where}`)
  }
}

/** Read src/client/index.js and write the wrapped lib/client.js. */
export async function buildClient() {
  const source = await readFile(join(root, 'src', 'client', 'index.js'), 'utf8')
  const bundle = wrapClient(source)
  assertLoadableInBrowser(bundle)
  const out = join(root, 'lib', 'client.js')
  await writeFile(out, bundle, 'utf8')
  return out
}
