/**
 * Wraps the src/client parts into the DSH browser module-loader shape every
 * published client plugin uses (window.__ModuleLoader__.load), producing the
 * single-file lib/client.js that package.json exports as "./client".
 *
 * Like the sibling otools-git plugin the browser half is far too big for one
 * file, so it is kept as an ORDERED LIST of fragments concatenated inside a
 * single IIFE. They share one lexical scope exactly as one big file would: a
 * fragment may use anything an earlier fragment declared, and function
 * declarations hoist across the whole bundle. Every fragment is a plain script
 * body — no IIFE, no import/export — and every top-level name must be unique
 * across the list (`npm run check` catches a collision as a syntax error).
 *
 * `src/shared/lang.js` is INLINED rather than listed: it is an ES module the host
 * half imports, so the export keywords are stripped here. That keeps one copy of
 * the locale parser instead of the hand-mirrored copy the sibling plugins pay
 * for.
 *
 * The client source is dependency-free vanilla DOM — xterm.js is loaded at
 * runtime from the plugin's own /vendor route, not bundled — so the loader
 * `require` argument is simply unused. The inner IIFE assigns `module.exports`
 * when it sees a CommonJS `module`, which is exactly what the factory provides.
 *
 * @module dsh-plugin-otools-term/scripts/wrap-client
 */
import { readFile, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = dirname(dirname(fileURLToPath(import.meta.url)))

/** Loader plugin id (matches the package name and the cordis.patch.yml row). */
export const PLUGIN_ID = 'dsh-plugin-otools-term'

/**
 * Concatenation order. Roughly: vocabulary → i18n → helpers → styles → model →
 * transport → widgets → terminal → panes → dialogs → shell → boot. `boot.js`
 * must stay last: it both defines apply() and performs the module.exports
 * assignment.
 */
export const CLIENT_PARTS = [
  'vocab.js',
  'i18n.js',
  'dom.js',
  'styles.js',
  'model.js',
  'api.js',
  'icons.js',
  'widgets.js',
  'themes.js',
  'vendor.js',
  'terminal.js',
  'editor.js',
  'sftp.js',
  'transfers.js',
  'servers.js',
  'forward.js',
  'desktop.js',
  'aibar.js',
  'settings.js',
  'shell.js',
  'boot.js',
]

/** Shared ES modules inlined ahead of the fragments (export keywords stripped). */
export const SHARED_PARTS = ['lang.js']

/** Generated-file banner (plain ASCII comment). */
export const GENERATED_HEADER = [
  '/**',
  ' * dsh-plugin-otools-term client bundle - GENERATED by scripts/wrap-client.mjs.',
  ' * Do not edit; the source of truth is src/client/*.js (npm run build).',
  ' */',
  '',
].join('\n')

/**
 * Turn one ES module into a plain script body: drop the `export` keyword from
 * declarations and delete bare re-export lines. Only used for the small
 * shared/*.js modules, whose exports are all `export const` / `export function`.
 */
export function stripModuleSyntax(source) {
  return String(source)
    .replace(/^export\s+(const|let|var|function|class|async)\b/gm, '$1')
    .replace(/^export\s*\{[^}]*\}\s*;?\s*$/gm, '')
}

/** Wrap the ordered client fragments for the DSH module loader. */
export function wrapClient(parts) {
  const body = parts
    .map((part) => {
      const source = String(part.source).replace(/\s+$/, '')
      return `// ===== ${part.name} =====\n${source}`
    })
    .join('\n\n')
  return (
    GENERATED_HEADER +
    'window.__ModuleLoader__.load({\n' +
    `  id: '${PLUGIN_ID}',\n` +
    '  factory: (require) => {\n' +
    '    var module = { exports: {} };\n' +
    '    var exports = module.exports;\n' +
    '    (function () {\n' +
    "      'use strict';\n" +
    `${body}\n` +
    '    })();\n' +
    '    return module.exports;\n' +
    '  }\n' +
    '});\n'
  )
}

/** Read every fragment and write the wrapped lib/client.js. */
export async function buildClient() {
  const parts = []
  for (const name of SHARED_PARTS) {
    const source = await readFile(join(root, 'src', 'shared', name), 'utf8')
    parts.push({ name: `src/shared/${name} (inlined)`, source: stripModuleSyntax(source) })
  }
  for (const name of CLIENT_PARTS) {
    parts.push({ name: `src/client/${name}`, source: await readFile(join(root, 'src', 'client', name), 'utf8') })
  }
  const out = join(root, 'lib', 'client.js')
  await writeFile(out, wrapClient(parts), 'utf8')
  return out
}
