/**
 * Wraps src/client/index.js into the DSH browser module-loader shape every
 * published client plugin uses (window.__ModuleLoader__.load), producing the
 * single-file lib/client.js that package.json exports as "./client".
 *
 * The client source is dependency-free vanilla DOM: it never requires anything, so
 * the loader `require` argument is simply unused. The inner IIFE assigns
 * `module.exports` when it sees a CommonJS `module` — exactly what the factory
 * provides — and the factory returns it.
 *
 * The bundle is checked in script mode before it is written. The browser loads
 * `lib/client.js` as a CLASSIC script, where a surviving `import` is a SyntaxError:
 * the file then never runs, `__ModuleLoader__.load` is never called, and the only
 * symptom is a loader message about a plugin that loaded without registering.
 * `node --check` cannot catch it because package.json says `type: module`.
 *
 * @module dsh-plugin-otools-dbm/scripts/wrap-client
 */
import { readFile, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import vm from 'node:vm'

const root = dirname(dirname(fileURLToPath(import.meta.url)))

/** Loader plugin id (matches the package name and the cordis.patch.yml row). */
export const PLUGIN_ID = 'dsh-plugin-otools-dbm'

/** Generated-file banner (plain ASCII comment). */
export const GENERATED_HEADER = [
  '/**',
  ' * dsh-plugin-otools-dbm client bundle - GENERATED by scripts/wrap-client.mjs.',
  ' * Do not edit; the source of truth is src/client/index.js (npm run build).',
  ' */',
  '',
].join('\n')

/** Wrap one client source file for the DSH module loader. */
export function wrapClient(source) {
  const body = String(source).replace(/\s+$/, '')
  return (
    GENERATED_HEADER
    + 'window.__ModuleLoader__.load({\n'
    + `  id: '${PLUGIN_ID}',\n`
    + '  factory: (require) => {\n'
    + '    var module = { exports: {} };\n'
    + '    var exports = module.exports;\n'
    + `${body}\n`
    + '    return module.exports;\n'
    + '  }\n'
    + '});\n'
  )
}

/** Refuse to write a bundle the browser could not load as a classic script. */
export function assertLoadableInBrowser(bundle) {
  const offenders = []
  bundle.split(/\r?\n/).forEach((line, index) => {
    const trimmed = line.trim()
    if (/^import[\s{('"*]/.test(trimmed) || /^export[\s{*]/.test(trimmed)) {
      offenders.push(`${index + 1}: ${trimmed.slice(0, 100)}`)
    }
  })
  if (offenders.length > 0) {
    throw new Error(
      'client bundle still contains ESM syntax, which a classic script cannot load:\n'
      + offenders.join('\n'),
    )
  }
  // Script mode, not module mode: this is exactly how the browser will parse it.
  new vm.Script(bundle, { filename: 'lib/client.js' })
}

/** Read src/client/index.js and write the wrapped lib/client.js. */
export async function buildClient() {
  const source = await readFile(join(root, 'src', 'client', 'index.js'), 'utf8')
  const bundle = wrapClient(source)
  assertLoadableInBrowser(bundle)
  const out = join(root, 'lib', 'client.js')
  await writeFile(out, bundle, 'utf8')
  return out
}
